### PR TITLE
[14.0][mig] website_menu_by_user_status

### PR DESCRIPTION
**Pull request by matteoopenf**

### CODE REVIEW

**Comment by matteoopenf** [comment]
@OCA/community-maintainers  any idea to fix?

**Review by patrickt-oforce — APPROVED** [review]

**Comment by matteoopenf** [comment]
@OCA/website-maintainers  review?

**Comment by matteoopenf** [comment]
@OCA/website-maintainers review?

**Comment by matteoopenf** [comment]
@OCA/website-maintainers  review?

**Review by tarteo — APPROVED** [review]
Tested locally, works fine. :+1: 

Just a comment (not part of the migration).  It would be nice to make the menu settings editable using the website editor. 
Here:
image

**Pull request merged**
