### PR TITLE
[16.0][MIG] website_require_login: Migration to 16.0

### PR DESCRIPTION
**Pull request by hailangvn**

### CODE REVIEW

**Comment by Aldeigja** [comment]
Hi @hailangvn
I've been trying to check functionality, it seems the latest commit is  causing "500: Internal Server Error" on runboat, could you check this?

**Comment by hailangvn** [comment]
> I've been trying to check functionality, it seems the latest commit is causing "500: Internal Server Error" on runboat, could you check this?

The error has been fixed. Thanks for your notification.

**Review by Aldeigja — APPROVED** [review]
Functional ok!

**Review by geomer198 — COMMENTED** [review]
Could you add tests for `_dispatch` and `_check_require_auth` functions.

**Review by geomer198 — APPROVED** [review]
Code review ok!

**Pull request merged**
