### PR TITLE
[website_portal] After non employee user is logged, redirect to website main page.

### PR DESCRIPTION
**Pull request by sergio-teruel**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This branch seems a bit mixed between PRs.

**Comment by sergio-teruel** [comment]
@pedrobaeza solved mix

**Comment by pedrobaeza** [comment]
You can propose this also to Odoo/OCB in 9.0

**Comment by rafaelbn** [comment]
:+1: if propse to OCB please refer this PR please, thanks

**Pull request closed without merging**
