### PR TITLE
Update website_no_crawler to 9.0

### PR DESCRIPTION
**Pull request by RoelAdriaans**
Updated module to 9.0

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1: travis errors unrelated

**Comment by hbrunn** [comment]
@RoelAdriaans-B-informed but maybe it's a good idea anyways to make lessc work in this PR:
- add npm to https://github.com/OCA/website/blob/9.0/.travis.yml#L7
- say `npm install less less-plugin-clean-css` at https://github.com/OCA/website/blob/9.0/.travis.yml#L30
- add `~/node_modules/less/bin` to the path

**Comment by hbrunn** [comment]
current maintainer tools support lessc, so I just restarted travis

**Comment by hbrunn** [comment]
now you need website_account or whatever the 9.0 equivalent is

**Comment by RoelAdriaans** [comment]
@hbrunn I don't get why id needs website_account ? 
This module edits a view created by the `website` module. The travis errors are in website_portal_sale, not related to this pull request.

I think the travis changes should be in a separate pull request and does not matter to this module. I will rebase if the website branch is updated if it's still needed.

**Comment by rafaelbn** [comment]
Hi @hbrunn What must be fixed?

**Comment by pedrobaeza** [comment]
Please squash your commits in one

**Comment by RoelAdriaans** [comment]
@pedrobaeza Done.

**Pull request merged**
