### PR TITLE
[12.0][ADD]website_hide_invoice

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
**Added** 

>> website_hide_invoice

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The invoices in the portal doesn't require website (only portal), so you shouldn't call it this way and don't be hosted here.

**Comment by marcelsavegnago** [comment]
Considering the non-dependency of the website module, it may be better to host the module at https://github.com/OCA/account-invoicing

**Comment by dreispt** [comment]
Makes sense.
What about naming it `account_portal_hide_invoice`?

**Comment by dreispt** [comment]
@hpatelserpentcs Can you please rename and move to https://github.com/OCA/account-invoicing ?

**Comment by HaraldPanten** [comment]
> Makes sense.
> What about naming it `account_portal_hide_invoice`?

I like your `account_portal_hide_invoice` module name suggestion. It suits well 👍

**Pull request closed without merging**
