### PR TITLE
Website Portal Enhanced module.

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**
This module depends on website portal module which extends the functionality of website portal module and adds support for displaying or edit the image of user.
It will also changes the look end feel of my account.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Ping please!

**Comment by rafaelbn** [comment]
Nice to test @danielgz @yajo @sergio-incaser @carlos-incaser

**Comment by rafaelbn** [comment]
Nice to test @dgzurita @yajo @sergio-incaser @carlos-incaser

**Comment by rafaelbn** [comment]
Hi @JayVora-SerpentCS, thanks a lor for this module!

[FIX] you totally remove the http://3139568-95-9085ef.runbot1.odoo-community.org/my/home view with quotations, orders, invosices and payments. Please fix this.

Module's name I have to think about it

In my opinion result is not good enough, take care on the example of LInkedin or Facebook where "some people" change picture and edit profije everyday. Picture 99% cases is in the left side of name and not in a Menu (I recomend to change it)

**Comment by pedrobaeza** [comment]
Shouldn't this be integrated in current website_portal module?

**Comment by ghost** [comment]
Thank you for the review.

@rafaelbn I will check the issue and will do the needful.

@pedrobaeza Yes we will make another PR for it.

**Comment by yajo** [comment]
`website_portal` is a backport from 9.0. I'd prefer not to diverge too much, or forward-porting it will be harder.

**Comment by rafaelbn** [comment]
@pedrobaeza IMHO it nor good idea modify a backport from v9, better do this in a separate module. Inf fact nor everyone want/need this enhance. Agree with @yajo to maintain this in a separate PR

**Comment by andhit-r** [comment]
Hi @JayVora-SerpentCS runbot is failing. Would you kindly rebase it so I can test it on runbot?

**Comment by rafaelbn** [comment]
cc @sergio-incaser @carlos-incaser

**Comment by pedrobaeza** [comment]
@JayVora-SerpentCS are you going to work on this more? Maybe it's interesting to backport this already merged module instead: https://github.com/OCA/website/tree/9.0/website_portal_v10

**Comment by simahawk** [comment]
@JayVora-SerpentCS closing as it's on 8.0 and no action since 2 yrs.
Feel free to re-open it.

**Pull request closed without merging**
