### PR TITLE
[8.0][website_calendar_snippet] DST error fix

### PR DESCRIPTION
**Pull request by tarteo**
Fixes the problem explained in #185.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you point me to an example that I can try on runbot so I can see before and after?

**Comment by rafaelbn** [comment]
@tarteo could you clarify this PR? Thanks

**Comment by tarteo** [comment]
@rafaelbn The current module does not take DST (https://en.wikipedia.org/wiki/Daylight_saving_time) into account. This PR fixes that issue.

**Comment by lasley** [comment]
@tarteo - I'm not so sure if this adds up because the delta is created in UTC from Time A and Time B. These UTC times were generated via Tz aware context Datetimes on the way from browser to Odoo, which would account for Time A being in DST and Time B being outside of it.

I can, however, see a theoretical issue if User A is in a timezone that does not have DST. They schedule an appointment for User B that is in a DST tz. Looking at the calendar_event code, I believe that is an edge case that would yield a perceived global DST issue.

Can you please provide a before/after example? 

P.S. - I hold an eternal hate for whoever decided DST was a good idea.

**Comment by tarteo** [comment]
@lasley

>  I'm not so sure if this adds up because the delta is created in UTC from Time A and Time B. These UTC times were generated via Tz aware context Datetimes on the way from browser to Odoo, which would account for Time A being in DST and Time B being outside of it.

When the calendar event (or any object with a date) is created it converts the tz aware date to tz unaware date (database). When shown in e.g. a form the tz unaware date gets client side converted to tz aware date (correct me if I'm wrong)

> I can, however, see a theoretical issue if User A is in a timezone that does not have DST. They schedule an appointment for User B that is in a DST tz. Looking at the calendar_event code, I believe that is an edge case that would yield a perceived global DST issue.

The required offset is calculated client side, so I think this is not an issue (maybe I misunderstood your issue).

Before / after:

dstfix

http://www.timeanddate.com/time/change/netherlands/amsterdam

**Comment by lasley** [comment]
@tarteo TBH I see this as a core calendar issue due to lack of true time zone support. The calendar seems to be fully naive in even the most simple instances, such as:
- Admin User in `US/Hawaii` creates appointment for 11:00 
- Admin adds Demo User as attendee
- Demo User in `US/Pacific` sees 11:00

**Comment by tarteo** [comment]
@lasley, dst is applied on the web_calendar module, e.g. I make an appointment for 11:00; on the core calendar it shows the correct time, but on the website_calendar_snippet it shows 10:00 (depending on the dst). The module (website_calendar_snippet) is already applying the user's time zone.

**Comment by lasley** [comment]
@tarteo - Whoops seems I missed this comment. 

Got it, I understand now. Your fix does work, and makes the times correlate w/ what you would see in the backend calendar.

This is still technically a datetime naive calendar, but so is the real one - which is an issue for another day/PR. 👍  from me

**Comment by ehahouimohssine** [comment]
:+1:

**Pull request merged**
