### PR TITLE
[WIP] Added SEO url handling for website views and blogs.

### PR DESCRIPTION
**Pull request by rruebner**
Hi,

I would to share my ideas for an improved url handling to have a better SEO relevance. It is work in progress and not finally done. You will find information in the README.rst files and below some additional notes.
# Structure

In general these changes will only affect the frontend. The backend urls won't be touched.

My intention was to create a base module website_seo and additional modules like website_seo_blog, website_seo_sale, etc. The base module contains the general handling of the SEO urls and especially the handling for qweb ir.ui.view records (the default odoo CMS pages).

The additional modules extend the SEO url handling for their specific scope. Means the website_seo_blog module handles the blog / blog post urls, the website_seo_sale module handles the product / product category urls etc. Currently the website_seo_blog module has an old SEO url approach which will be updated when the SEO url handling in the base module is fine and finished.
# How to use

Install the website_seo and website_seo_blog modules. After that you have to update the website module (more information in the README.rst files).
## ir.ui.view records

You will find a new menu entry in Settings -> Configuration -> Website Settings -> SEO Pages. It opens a list with all ir.ui.view records which have the type "qweb" and don't inherit another view. You can also manage the SEO fields in Settings -> Technical -> User Interface -> Views but I think you can manage the urls in a better way in the compact list view. Move your mouse over the "SEO Parent" field to see an example how the SEO urls are working. After you add the correct parents you have to add the SEO url levels manually for now. The automatically setup is not yet finished, see the "ToDo" section. Now you can open a view with the new url structure.
## blog urls

After the installation of the website_seo_blog module the blogs and blog posts are already updated with the SEO urls. See the README.rst file of this module for more information. But as I mentioned before this module is an old approach. If the website_seo module is finished the website_seo_blog module will be updated. This will also remove the fixed prefix "blog-" which you still have to use.
# ToDo

There are still some things to do. I marked them in the code as "ToDo". Here is a key list:
- add one additional check for the parent_id in SEO urls to ensure valid urls
- maybe rewrite the _dispatch() function in addons/website/models/ir_http.py to avoid double code using
- add automatically SEO url level updates on SEO url parent changes
- add SEO url level and parent changes when adding / updating the menu entries in the frontend and backend
# Drawbacks

Unfortunately the new fields in website.seo.metadata have some side effects. Like I described in "How to use" you have to update the website module after the website_seo / website_seo_blog module installation. The other issue is that the travis bot always fails because some fields are missing at the time the travis bot is running.

What do you think, is this approach useful or are there some more drawbacks I didn't see?

And can I leave the SEO relevant fields in website.seo.metadata and do some additional stuff or should I add these fields to all relevant models like blog or blog.post directly to ensure a happy travis bot?

### CODE REVIEW

**Comment by rruebner** [comment]
Just as information: I signed the Contributor License Agreement this year, I think it was in in mid-May.

**Comment by parthivgls** [comment]
You PR seems to be addressing some of the issues that are mentioned at https://github.com/odoo/odoo/issues/8246, like clean URL but another fear is that if some one takes this module as a based and start using other modules built on top of core-odoo modules, things might not work as expected. 

Rest seems pretty nicely done. :+1:  from my side

**Comment by rafaelbn** [comment]
Hi, thanks for this contribution.
- Please make a single PR for module. This PR has 2 modules. You must do 2 PRs
- Please follow the template from OCA https://github.com/OCA/maintainer-tools/tree/master/template/module
- Review README as said in template

**Comment by rafaelbn** [comment]
@rruebner could you review this PR?
Maybe you are interested in https://github.com/OCA/website/pull/200
cc @Yajo @pedrobaeza

**Comment by yajo** [comment]
Hi, me being the author of #200 I'm maybe not neutral enough, but I think #200's implementation is way simpler than this:
- It just overloads 1 method from `ir.http` object.
- No controllers changed.
- It adds a model which contains all origin-destination redirections, so you can batch-manage them.
- It works with _any_ URL, so mostly no need to have submodules such as `website_seo_blog`, etc.
- If you want to redirect all URLs by prefix (e.g. redirecting all `/blog/*` to `blog-`*), that should not be a very hard extension to #200, and could be configurable (to avoid those submodules I said above).
- LGPL.

But I like more in this PR that you have the UI in the promote menu, which is something I wanted but did not have time to get for mine. It would be another easy extension to #200 anyway.

**Comment by rafaelbn** [comment]
Hi @rruebner are you going to continue with this PR? As I said yoy must review https://github.com/OCA/website/pull/74#issuecomment-161158257
In this moment you must check modules already done like https://github.com/OCA/website/blob/8.0/website_seo_redirection
Please let me know, thanks.

**Comment by rruebner** [comment]
Hi @rafaelbn, I will check it next week.

**Comment by yajo** [comment]
I think this could be closed, #200 is merged.

**Pull request closed without merging**
