### PR TITLE
[FIX] website_no_crawler: don't translate

### PR DESCRIPTION
**Pull request by chienandalu**
robots.txt should not be translated in order to have any effect

cc @Tecnativa TT29159

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why the red ci?

**Comment by chienandalu** [comment]
Looks like the branch is red. I opened an issue: https://github.com/OCA/website/issues/832

**Comment by pedrobaeza** [comment]
OK, let's merge this manually being critical for the use of the module, for not waiting for the fix on the other test.

**Comment by pedrobaeza** [comment]
Is this applicable in upper versions?

**Comment by chienandalu** [comment]
It should

**Pull request merged**
