### PR TITLE
[MIG] website_portal_address: Migration to 12.0

### PR DESCRIPTION
**Pull request by mathben**
Depends on website_portal_contact https://github.com/OCA/website/pull/701

### CODE REVIEW

**Review by Tardo — CHANGES_REQUESTED** [review]
Please, preserve commit history and clean the PR to only have "website_portal_address" changes...

**Comment by HaraldPanten** [comment]
Hi @mathben ,

Are you going to continue this PR?

**Comment by mathben** [comment]
Hi @HaraldPanten , your help is appreciated. I need to merge first https://github.com/OCA/website/pull/701
Thanks

**Comment by HaraldPanten** [comment]
> Hi @HaraldPanten , your help is appreciated. I need to merge first #701
> Thanks

Sure, I will 👍

**Review by claudiagn — COMMENTED** [review]
@mathben let me know when you do the merge so we can review this 👍

**Comment by mathben** [comment]
Close, continue into #883

**Pull request closed without merging**
