### PR TITLE
[16.0][MIG] website_google_tag_manager: Migration to 16.0

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Review by flotho — APPROVED** [review]
code reviw,  LGTM

**Comment by bvanjeelharia** [comment]
Hello @flotho , can the pull request be merged now?

Thanks

**Comment by pedrobaeza** [comment]
A second review must be done, and one proceeding from a PSC or maintainer. You can speed this up reviewing other PRs and asking in exchange that they review yours.

/ocabot migration website_google_tag_manager

**Review by JrAdhoc — APPROVED** [review]
Code review LGTM +1

**Pull request merged**
