### PR TITLE
[FIX][8.0] website_cookie_notice: added cookiecuttr.css

### LINKED ISSUE #135: [8.0][website_cookie_notice] cookiecuttr.css forgotten?
9.0 version has it, but not 8.0...

### PR DESCRIPTION
**Pull request by Tardo**
This PR fix #135 

Adds the cookiecuttr.css and includes the necessary line in assets_frontend

### CODE REVIEW

**Comment by yajo** [comment]
Why do you need that at all?

**Comment by rafaelbn** [comment]
More than a fix this is an improvement.

Without this fix:

without

With this improvement:

with

Customer view, I think it's better with this improvement

Why not to do this improvement?

**Comment by yajo** [comment]
Don't you think styling should be left for themes?

**Comment by dgzurita** [comment]
Tested in runbot :+1:

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by pedrobaeza** [comment]
Is this still needed?

**Comment by yajo** [comment]
Was it ever? https://github.com/OCA/website/pull/137#issuecomment-168719663

**Comment by pedrobaeza** [comment]
Well, it's basic styling that can even be taken as template for themes, don't you think?

**Comment by yajo** [comment]
Honestly, not. Read the minified CSS. Most of what it does is give colors to the elements, and colors are one of the most inherent parts of any theme. It could give some placement, but not colors, borders, etc. Oh and only minified? Please provide the full readable source, Odoo minifies automatically.

**Comment by pedrobaeza** [comment]
OK, I see. I close then.

**Comment by Tardo** [comment]
Is nice to see that you install an app that not work well out of the box... what is the problem for overwrite a CSS class?

Where are minified? the CSS aren't using YUI CSS compression algorithm or something like that :/

**Comment by pedrobaeza** [comment]
@CytraL, why it doesn't work?

**Comment by Tardo** [comment]
Default Odoo Theme not apply any css rule no? You will need install cookies and a theme that apply style to cookies or made one... a.k.a cookies module not works well standalone... and idk if a theme that i bought applies some css rules to this element... and this element is needed by legal imposition.

And yes, it works but seems ugly xD
(Sry for my bad english)

**Comment by pedrobaeza** [comment]
Honestly I don't see the default as ugly, and if you see so, then that's the purpose of custom themes. Maybe I see uglier your new aspect...

**Comment by Tardo** [comment]
Oh not my style... is how Odoo works in the past.

**Comment by Tardo** [comment]
But ok... i will need make a theme. No problem. Cheers!

**Comment by pedrobaeza** [comment]
OK, let's see the opinion of other members of the community, but seeing the time this is opened, I see little interest in the change...

**Comment by yajo** [comment]
Hi @CytraL, thank you very much for your contribution. Sorry, I did not want to offend you, let me explain my points.

If you don't like the layout, please feel free to change it in a PR, but for the same reason nobody wants elements with a hardcoded `style` attribute, nobody wants hardcoded colors for a given part of the website.

Current module's color schema is directly inherited by the underlying chosen bootstrap theme, and that's one of current design's strengths. In fact, the code you are trying to push was removed on purpose just because of this reason.

So, in general terms, website addons try to adhere as much as possible to vanilla bootstrap to allow themes to change all things magically.

And about the minification, publishing a minified CSS file is similar to sending a blob. In an open source project, we want the source. And as stated above, Odoo does minification automatically for you.

Closing a PR does not mean it will never be accepted, you can always open a new one, but please next time provide human-readable code wherever possible and prefer agnostic styling above opinionated one.

Thanks!

**Comment by Tardo** [comment]
@Yajo no problem. Thanks for recommendations...

P.S: You can see the older file... i have not touched anything:
 https://github.com/OCA/website/blob/9.0/website_cookie_notice/static/src/css/cookiecuttr.css

**Comment by yajo** [comment]
I know the file, [I removed it](https://github.com/OCA/website/commit/e41a08f0852c05a0014505cf01a97662eb340e5c#diff-55fb7da87a8524587e8ef4a76d4902e2). :wink:

**Pull request closed without merging**
