### PR TITLE
[FIX] checkout() without self

### PR DESCRIPTION
**Pull request by Endika**

### CODE REVIEW

**Comment by yvaucher** [comment]
@Endika Thanks for the fix :+1: 

Have you signed already the CLA?

**Comment by pedrobaeza** [comment]
:+1:

**Comment by JavierIniesta** [comment]
:+1:

**Comment by IObregon** [comment]
:+1:

**Comment by IgorPastor** [comment]
:+1:

**Comment by Erly** [comment]
:+1:

**Comment by antespi** [comment]
:+1:

**Pull request merged**
