### PR TITLE
10.0 website multi theme fixes

### PR DESCRIPTION
**Pull request by yelizariev**
Fixes for https://github.com/OCA/website/pull/443

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you explain the rationale of this?

**Comment by yelizariev** [comment]
Both updates (not in doc, ``with_context`` call) were made for initial version of updates in #443. Later the PR was remade, but those updates left the same.

**Comment by yelizariev** [comment]
Short explanations are in commit descriptions

**Review by pedrobaeza — APPROVED** [review]

**Comment by yelizariev** [comment]
I'll rebase this after https://github.com/OCA/website/pull/453

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by yelizariev** [comment]
Rebased and checks have passed :green_apple:

**Comment by pedrobaeza** [comment]
OK, we can merge then.

**Pull request merged**
