### PR TITLE
[15.0][MIG] website_portal_contact

### PR DESCRIPTION
**Pull request by bobslee**

### CODE REVIEW

**Review by ioans73 — APPROVED** [review]
Functional review

**Comment by bobslee** [comment]
Can we just remove the website tours (JavaScript)?
I also don't know how to read (interpret) those failed CI jobs. Any help appreciated.

**Comment by pedrobaeza** [comment]
The tours intend to check the behavior as if you were clicking on the frontend part. They assure that it works as intended.

**Comment by bobslee** [comment]
Ok thanks. 
Any guidance, recommendations for following:
1. How can I run the tours in v15 ?
2. What do I need to fix for this PR?

**Comment by pedrobaeza** [comment]
They run the usual way: `--test-enable ...`

About the error, the xpath locator indicates what can't be found, and thus, the thing that have changed.

**Comment by bobslee** [comment]
I can't find the logging of the failed xpath indicator. Do you have a link please?

I shall run the tests locally and try to analyze, fix things.
For me, the jobs output (pre-commit etc) is still a bit hard to grasp, don't understand yet.

**Comment by pedrobaeza** [comment]
I'm seeing the GH output and indeed is not telling too much detail. Not sure why, as myself I'm not an export of tour tests. Maybe @ivantodorovich can tell, which gave a talk about this on last OCA days.

**Comment by bobslee** [comment]
Thanks for discussing and checking @pedrobaeza.
Where can I find the `xpath` error, in the output logs?

Anyway, I shall run locally when I find the time.

**Comment by ivantodorovich** [comment]
If the tour fails you can find a screenshot in the `/tmp` directory (or you can configure a different output path with the `--screenshots /home/me/path/to/screenshots` cli argument)

You can also ask for a video, too, with the `--screencasts /home/me/path/to/screencasts` cli argument

More about them in official docs: 
https://www.odoo.com/documentation/16.0/developer/cli.html#cmdoption-odoo-bin-screenshots
https://www.odoo.com/documentation/16.0/developer/cli.html#cmdoption-odoo-bin-screencasts

Also, tours are a list of steps simulating user actions, defined with jquery selectors.
These jquery selectors might not work after a migration, because possibly the html structure changed in odoo core. The selectors need to be adapted for the new version. That might be the reason why the tour is failing

**Pull request closed without merging**
