### PR TITLE
[16.0][MIG] website_snippet_country_dropdown: Migration to 16.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago 

#913

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by kaynnan** [comment]
ping @OCA/website-maintainers

**Review by NICO-SOLUTIONS — COMMENTED** [review]
Functional review. LG

**Comment by kaynnan** [comment]
ping @OCA/website-maintainers

**Comment by pedrobaeza** [comment]
Please rebase to check runboat.


/ocabot migration website_snippet_country_dropdown

**Comment by edlopen** [comment]
Hello @kaynnan , I am interested in having this module migrated. Thanks in advance!

**Comment by kaynnan** [comment]
@pedrobaeza @edlopen 

PR updated with rebase on origin/16.0, ready for review

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
