### PR TITLE
[ADD] website_sale_odoo_debranding: module to remove powered by in portal

### PR DESCRIPTION
**Pull request by cubells**
If user has installed module `website_sale`, then a `Powered by odoo` link is shown in portal views.
Before:
before

With this module:
after

I've created another module to avoid install website_sale if it is no needed.

### CODE REVIEW

**Review by misern2 — APPROVED** [review]
:+1:  LGTM

**Review by ferranmateu — APPROVED** [review]
Funcional review ok

**Comment by pedrobaeza** [comment]
The portal is there no matter if `website_sale` is installed. Or the sentence is added only when `website_sale` is there?

**Review by claudiagn — APPROVED** [review]
Functional review done

**Comment by cubells** [comment]
@pedrobaeza 

> The portal is there no matter if website_sale is installed. Or the sentence is added only when website_sale is there?

Only when website_sale is installed.

**Comment by pedrobaeza** [comment]
Please check because that's not true. Without `website_sale`, you have the portal for seeing quotations, invoices, etc. The doubt is if the text appears before, or installing this module. Are you sure it doesn't appear only with website?

**Comment by cubells** [comment]
You are right @pedrobaeza 

Thanks for detect the mistake.

I close this pr. Please merge the other one.

**Pull request closed without merging**
