### PR TITLE
[FIX] Tests

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I made also an attempt to greenify the branch here: https://github.com/OCA/website/pull/75, but without success.

**Comment by StefanRijnhart** [comment]
Thanks @pedrobaeza, I'm using some of your changes!

**Comment by StefanRijnhart** [comment]
@pedrobaeza together we did it! Travis is green. Apparently, you were very close in #75.

Asking original module authors @antespi and @eLBati for reviews.

**Comment by pedrobaeza** [comment]
Thank you so much for handling this :+1: 

Maybe you can squash the commits to get a cleaner history.

**Comment by StefanRijnhart** [comment]
Cleaned up the history slightly but keeping meaningful commit messages and attribution.

**Comment by antespi** [comment]
:+1: Cool! Thanks all

**Comment by lmignon** [comment]
:+1:  Thank you for the fix!

**Comment by pedrobaeza** [comment]
Merging!

**Comment by eLBati** [comment]
Thanks!

**Pull request merged**
