### PR TITLE
10.0 mig website canonical url

### PR DESCRIPTION
**Pull request by reinka**
Migration to v10. 

Additionally, replaced relative URLs by absolute ones, according to these comments: https://github.com/OCA/website/pull/299#pullrequestreview-35771815

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't there any 9.0 commit to bring? Have you used migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0?

**Comment by reinka** [comment]
@pedrobaeza Sorry, but what do you mean by "Isn't there any 9.0 commit to bring?"?

**Comment by pedrobaeza** [comment]
Well, have you run the commands specified in the migration guide? If so, this add any change since the 10.0 branch fork in your PR.

**Comment by reinka** [comment]
@pedrobaeza I'm new to all this. I'll have a look at the requirements in your link and get back to you once I've taken care of it. Please bear with me.

**Comment by reinka** [comment]
@pedrobaeza I reverted all my commits and proceeded as required in your link. Please let me know if I've mistaken/missed something.

**Comment by pedrobaeza** [comment]
Perfect, now you only need to remove the initial commits + reverts instead of keeping them. If you don't know how, tell me and I'll do it.

**Comment by reinka** [comment]
@pedrobaeza Tried to figure it out myself. I rebased and dropped all the commits you mentioned. Was this the correct way?

**Comment by pedrobaeza** [comment]
Yeah, it seems so!

Now go for the green Travis.

**Comment by reinka** [comment]
@pedrobaeza I'm confused. I've checked the details of the travis build, there it says: 

`Module website_seo_redirection: 1 failures, 0 errors`

It seems all generated errors are due to `website_seo_redirection`. However, I didn't change anything regarding `website_seo_redirection`. Am I missing anything?

**Comment by pedrobaeza** [comment]
@Yajo can you check about the fail on website_seo_redirection?

**Comment by yajo** [comment]
Maybe you need rebasing?

**Comment by reinka** [comment]
@Yajo Sorry to ask, but what kind of rebasing? I rebased before by dropping unnecessary commits.

**Comment by pedrobaeza** [comment]
The main branch is now green, so if you make (assuming `origin` remote is OCA one):
```
git fetch origin
git rebase origin/10.0
git push -f
```

**Comment by reinka** [comment]
`origin` remote isn't OCA, since I forked it. I tried to 
`git remote add upstream https://github.com/OCA/website`  
`git fetch upstream` 
`git rebase upstream/10.0` and finally 
`git push -f`.

That didn't work. After that I ran your commands and it did work. If someone could explain why, I'd really appreciate it.

**Comment by pedrobaeza** [comment]
The rebase hasn't gone correctly.

**Comment by simahawk** [comment]
this and the other duplicated PR #413 are superseeded by https://github.com/OCA/website/pull/449

**Pull request closed without merging**
