### PR TITLE
[13.0][MIG] website_google_tag_manager

### PR DESCRIPTION
**Pull request by bjornbillen**

### CODE REVIEW

**Review by tarteo — APPROVED** [review]
Code LGTM

**Review by pedrobaeza — APPROVED** [review]
Next time, please split black, isort thing from the migration itself as explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by pedrobaeza** [comment]
Please rebase and pass pre-commit for reformatting things

**Comment by bjornbillen** [comment]
> Please rebase and pass pre-commit for reformatting things

No problem. Will do. I can see the bot is using prettier in the pre-commit now. That's why the checks are failing now and not before.

**Comment by bjornbillen** [comment]
> Next time, please split black, isort thing from the migration itself as explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

Excuse me, must have overlooked this guideline.

**Pull request merged**
