### PR TITLE
[Mig] Website_lazy_load_image Migration to 13

### PR DESCRIPTION
**Pull request by yassine-teoshore**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Review by tarteo — CHANGES_REQUESTED** [review]
Tested functionality: images won't load. 

The whole editor code is missing.

**Comment by simahawk** [comment]
replaced by https://github.com/OCA/website/pull/735

**Comment by simahawk** [comment]
@yassine-teoshore thanks for your contrib. As you see the PR was incomplete and @tarteo created a new one. If you still like to contribute to this addon, please go to #735 and do a review :wink:

**Pull request closed without merging**
