### PR TITLE
11.0 mig website_form_builder

### PR DESCRIPTION
**Pull request by Daemo00**
Hi,
migrating website_form_builder to v11, please check.

Thanks

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis status

**Comment by Daemo00** [comment]
Looking into it

**Comment by OsoTranquilo** [comment]
Everything seems to work well.
Create a form and make it possible to add fields and assign characteristics.

**Review by yajo — CHANGES_REQUESTED** [review]
It looks good, but [there's something failing in Travis](https://travis-ci.org/OCA/website/jobs/394238879#L1302).

It seems a conflict with `website_multi_theme`, due to some test from that module not being very good written :confused: 

You can fix the test or configure Travis to test it separately. Maybe @yelizariev can help a bit in fixing the test...

**Comment by yelizariev** [comment]
I [reported eairler](https://github.com/OCA/website/pull/450#issuecomment-387215721) that it's a random error. You need to restart travis job to get it green. It's kind of difficult to reproduce it to debug and fix.

**Comment by yajo** [comment]
Thanks, I restarted the job, let's see.

I opened https://github.com/OCA/website/issues/487 so we can keep track of this problem until fixed.

**Comment by Daemo00** [comment]
@Yajo the issue with tests doesn't seem to be related to this PR, any change suggested here?

**Review by yajo — APPROVED** [review]
Sorry, I didn't get back to this, indeed it's not this PR fault, it looks pretty good.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
