### PR TITLE
[12.0][MIG] website_snippet_preset: Migration to v12

### PR DESCRIPTION
**Pull request by keylor2906**

### CODE REVIEW

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
Tested on runbot, it is working as expected

**Review by tbaden — CHANGES_REQUESTED** [review]
thanks for the work 👍 
please keep the commit history using [this](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch)

and please use the fragment [readme](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration)

and please fix these linting warnings:
************* Module website_snippet_preset
website_snippet_preset/static/src/js/website_snippet_preset.js:4: [W7903(javascript-lint), ] Use the function form of 'use strict'. [Error/strict]
website_snippet_preset/static/src/js/website_snippet_preset.js:4: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:13: [W7903(javascript-lint), ] Line 13 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:16: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:18: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:22: [W7903(javascript-lint), ] ["name"] is better written in dot notation. [Error/dot-notation]
website_snippet_preset/static/src/js/website_snippet_preset.js:23: [W7903(javascript-lint), ] Expected space(s) after "if". [Error/keyword-spacing]
website_snippet_preset/static/src/js/website_snippet_preset.js:23: [W7903(javascript-lint), ] Expected { after 'if' condition. [Error/curly]
website_snippet_preset/static/src/js/website_snippet_preset.js:24: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:29: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:34: [W7903(javascript-lint), ] 'EnterNameDialog' was used before it was defined. [Error/no-use-before-define]
website_snippet_preset/static/src/js/website_snippet_preset.js:35: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:36: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:37: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:41: [W7903(javascript-lint), ] Expected space(s) after "if". [Error/keyword-spacing]
website_snippet_preset/static/src/js/website_snippet_preset.js:42: [W7903(javascript-lint), ] 'OverwriteDialog' was used before it was defined. [Error/no-use-before-define]
website_snippet_preset/static/src/js/website_snippet_preset.js:50: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:51: [W7903(javascript-lint), ] 'self' is assigned a value but never used. [Error/no-unused-vars]
website_snippet_preset/static/src/js/website_snippet_preset.js:56: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:57: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:58: [W7903(javascript-lint), ] Line 58 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:58: [W7903(javascript-lint), ] Expected '===' and instead saw '=='. [Error/eqeqeq]
website_snippet_preset/static/src/js/website_snippet_preset.js:58: [W7903(javascript-lint), ] ["id"] is better written in dot notation. [Error/dot-notation]
website_snippet_preset/static/src/js/website_snippet_preset.js:62: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:67: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:68: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:69: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:74: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:77: [W7903(javascript-lint), ] Unexpected negated condition. [Error/no-negated-condition]
website_snippet_preset/static/src/js/website_snippet_preset.js:77: [W7903(javascript-lint), ] Expected { after 'if' condition. [Error/curly]
website_snippet_preset/static/src/js/website_snippet_preset.js:81: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:83: [W7903(javascript-lint), ] Expected { after 'else'. [Error/curly]
website_snippet_preset/static/src/js/website_snippet_preset.js:87: [W7903(javascript-lint), ] A space is required after ','. [Error/comma-spacing]
website_snippet_preset/static/src/js/website_snippet_preset.js:87: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:90: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:91: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:97: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:102: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:105: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:107: [W7903(javascript-lint), ] Line 107 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:109: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:110: [W7903(javascript-lint), ] ["arch"] is better written in dot notation. [Error/dot-notation]
website_snippet_preset/static/src/js/website_snippet_preset.js:112: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:113: [W7903(javascript-lint), ] ["id"] is better written in dot notation. [Error/dot-notation]
website_snippet_preset/static/src/js/website_snippet_preset.js:119: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:125: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:127: [W7903(javascript-lint), ] Unexpected console statement. [Error/no-console]
website_snippet_preset/static/src/js/website_snippet_preset.js:132: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:136: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:137: [W7903(javascript-lint), ] 'self' is assigned a value but never used. [Error/no-unused-vars]
website_snippet_preset/static/src/js/website_snippet_preset.js:141: [W7903(javascript-lint), ] Line 141 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:143: [W7903(javascript-lint), ] Line 143 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:144: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:145: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:149: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:153: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:156: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:160: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:161: [W7903(javascript-lint), ] 'self' is assigned a value but never used. [Error/no-unused-vars]
website_snippet_preset/static/src/js/website_snippet_preset.js:164: [W7903(javascript-lint), ] Line 164 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:165: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:168: [W7903(javascript-lint), ] Line 168 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:168: [W7903(javascript-lint), ] There should be no space before '}'. [Error/object-curly-spacing]
website_snippet_preset/static/src/js/website_snippet_preset.js:169: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:170: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:174: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_snippet_preset/static/src/js/website_snippet_preset.js:176: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:181: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
website_snippet_preset/static/src/js/website_snippet_preset.js:182: [W7903(javascript-lint), ] Missing semicolon. [Error/semi]


@pedrobaeza are css files still viable or is it needed to convert these to scss?

**Comment by keylor2906** [comment]
Fixed js lints, convert css to scss, added fragmented readme and keep commit history

**Comment by Axel-G** [comment]
i install it from keylors repository but i dont get a preset-menu-entry.

**Comment by tbaden** [comment]
thanks for the changes 👍 
just some minor things left in the travis logs:

************* Module website_snippet_preset
website_snippet_preset/static/src/js/website_snippet_preset.js:17: [W7903(javascript-lint), ] Line 17 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:19: [W7903(javascript-lint), ] Unexpected line break after this opening brace. [Error/object-curly-newline]
website_snippet_preset/static/src/js/website_snippet_preset.js:45: [W7903(javascript-lint), ] Unexpected line break after this opening brace. [Error/object-curly-newline]
website_snippet_preset/static/src/js/website_snippet_preset.js:61: [W7903(javascript-lint), ] Line 61 exceeds the maximum line length of 80. [Error/max-len]
website_snippet_preset/static/src/js/website_snippet_preset.js:157: [W7903(javascript-lint), ] Line 157 exceeds the maximum line length of 80. [Error/max-len]

**Review by tarteo — CHANGES_REQUESTED** [review]
The style of the snippet menu is not Odoo 12 like.

image

**Comment by Tardo** [comment]
@keylor2906 ping :)

**Review by claudiagn — COMMENTED** [review]
Agree with @tarteo , @keylor2906 !

**Pull request closed without merging**
