### PR TITLE
8.0 website snippet blog display post

### PR DESCRIPTION
**Pull request by gfcapalbo**
website_snippet_blog_display_post : a snippet to visualize a blog post on your website.

Depends on website_blog_layout_options, where a "snippet", feature is added.

Note: depends on  blog extension:   https://github.com/OCA/website/pull/226
Depends also on panameterized snippets addon https://github.com/OCA/website/pull/236

to be reviewed after these are OK

### CODE REVIEW

**Comment by gfcapalbo** [comment]
@all the build fails because I depend on a module website_blog_layout_options. should I wait for https://github.com/OCA/website/pull/226  to be merged before this MR?

**Comment by hbrunn** [comment]
can only be merged after #226 is. Meanwhile, rebase and squash commits

**Comment by gfcapalbo** [comment]
Closing this PR. Will propose a MR to @lmignon 's module and make all my snippets depend on it.

**Comment by hbrunn** [comment]
review runbot and travis

**Review by hbrunn — CHANGES_REQUESTED** [review]
there's a vim swap file checked in that you should remove from the repo

**Review by susport — COMMENTED** [review]
Please check in the runbot the dependencies to add

**Pull request closed without merging**
