### PR TITLE
[8.0][website_breadcrumb] Add breadcrumbs to any page

### PR DESCRIPTION
**Pull request by yajo**
This module allows to set up breadcrumbs and configure them from the website menu settings.

It fits all the logic in a template that can be called with `t-call`, for easy theming.

### CODE REVIEW

**Comment by rafaelbn** [comment]
cc @dgzurita

**Comment by dgzurita** [comment]
Works fine :+1:

**Comment by sergio-teruel** [comment]
:+1: Tested in runbot.

**Comment by rafaelbn** [comment]
I think it must be aligned, see:

**Comment by yajo** [comment]
@rafaelbn Thanks, fixed.

**Comment by lmignon** [comment]
Merged, too late... my colleague @JonathanNEMRY has developed the same functionality but as a snippet that can be placed where you want in your page... (PR will follow...)

**Comment by yajo** [comment]
That was my initial idea, but it was harder than it seemed. You will probably be able to reuse some of this anyway. Eager to see that PR :wink:

**Comment by lmignon** [comment]
@Yajo The code is already functional and has been developed before your PR. We'll try to rebase our work on yours..

**Comment by JonathanNEMRY** [comment]
Hi @Yajo 
here it is --> #141 
We extend your module and add a dynamic snippet

**Pull request merged**
