### PR TITLE
[IMP] pre-commit update

### PR DESCRIPTION
**Pull request by yajo**
Implement changes from OCA/maintainer-quality-tools#618, OCA/maintainer-quality-tools#628, OCA/maintainer-quality-tools#630 and https://github.com/OCA/maintainer-quality-tools/pull/631.

@Tecnativa TT20357 @sbidoul

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you write on current PRs for warning about the rebase + changes?

**Comment by yajo** [comment]
WIP until OCA/maintainer-quality-tools#630 is merged.

**Comment by yajo** [comment]
> Can you write on current PRs for warning about the rebase + changes?

I guess the bot will tell about the failures.

**Pull request merged**
