### PR TITLE
[website_seo_redirection][FIX][9.0] Avoid some weird 403 errors.

### PR DESCRIPTION
**Pull request by lasley**
This cherry picks fix for #222 for v9

cc @Yajo @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rafaelbn** [comment]
:+1:

**Comment by rafaelbn** [comment]
I tested in runbot without this fix and with this fix. Bug https://github.com/OCA/website/issues/222 is solved also in v9. I think this can be a quick merge

**Comment by pedrobaeza** [comment]
Let's do it then!

**Pull request merged**
