### PR TITLE
[Updated] Icons to match Odoo's design

### PR DESCRIPTION
**Pull request by jonisunz**

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This one seems quite similar to https://github.com/OCA/management-system/blob/13.0/mgmtsystem/static/description/icon.png and seems to not express well what the module does.

I would take the website module icon as base, and add a Google recaptcha screenshot (the basic square) in the side.

**Comment by jonisunz** [comment]
> I would take the website module icon as base, and add a Google recaptcha screenshot (the basic square) in the side.
Is it the blue square here?
image
Or you mean this logo?
image

**Comment by pedrobaeza** [comment]
Second logo seems good (without the Privacy - Terms line), thanks.

**Review by chienandalu — APPROVED** [review]

**Comment by chienandalu** [comment]
I'd say this can be cherry-picked in later versions

**Comment by pedrobaeza** [comment]
Yes, cherry-picked for v13 at 07a6a668e7845a5fdbc790b91cb2381a02d2fb65

**Pull request merged**
