### PR TITLE
14.0 Mig Website Crm Privacy Policy

### PR DESCRIPTION
**Pull request by ska-ibees**
Migrated following standard OCA procedure:

Code updated w.r.t change in Odoo core
Readme updated using oca-gen-addon-readme

### CODE REVIEW

**Comment by ska-ibees** [comment]
Stuck on this error:

ERROR: Could not find a version that satisfies the requirement odoo14-addon-website_legal_page (from odoo14-addon-website_crm_privacy_policy->-r test-requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for odoo14-addon-website_legal_page (from odoo14-addon-website_crm_privacy_policy->-r test-requirements.txt (line 1))
The command "travis_install_nightly" failed and exited with 1 during .

**Comment by emagdalenaC2i** [comment]
@ska-ibees I think this fail because website_legal_page isn't merged.
See https://github.com/OCA/l10n-spain/pull/1491#issuecomment-710906974

**Comment by ska-ibees** [comment]
> @ska-ibees I think this fail because website_legal_page isn't merged.
> See [OCA/l10n-spain#1491 (comment)](https://github.com/OCA/l10n-spain/pull/1491#issuecomment-710906974)

@emagdalenaC2i Thank you for looking into it. I suspected it could be the reason that's why I migrated website_legal_page first that has passed Travis and runbot (Excited as it was my first PR 😊 ) but hasn't merged yet.

**Comment by ioans73** [comment]
Tested on dev instance

**Review by ioans73 — APPROVED** [review]

**Comment by ska-ibees** [comment]
Could anyone please review and merge this one? Last time it failed because website_legal_page wasn't merged at that time.

**Comment by fuentes73** [comment]
@ska-ibees could you rebase 14.0?

**Review by claudiagn — APPROVED** [review]
functional review ok! 👍

**Comment by ska-ibees** [comment]
> @ska-ibees could you rebase 14.0?

Do I need to create a new PR?

**Comment by ska-ibees** [comment]
`Obtaining odoo14-addon-website_crm_privacy_policy from file:///home/travis/build/OCA/website/setup/website_crm_privacy_policy#egg=odoo14-addon-website_crm_privacy_policy (from -r test-requirements.txt (line 1))

ERROR: Could not find a version that satisfies the requirement odoo14-addon-website_legal_page (from odoo14-addon-website_crm_privacy_policy->-r test-requirements.txt (line 1)) (from versions: none)

ERROR: No matching distribution found for odoo14-addon-website_legal_page (from odoo14-addon-website_crm_privacy_policy->-r test-requirements.txt (line 1))`

Could any one please help to understand this error and what needs to be done to fix it? Apparently it looks like 'website_legal_page'  which is the dependency of this module was not found during build. But as mentioned earlier, that module is already merged and available in the repo.

**Comment by manuelregidor** [comment]
Hi @ska-ibees. Don't you think that the reason for the error could be that you made the commit before the module website_legal_page was merged? Have you tried rebasing?

**Comment by ska-ibees** [comment]
@manuelregidor thanks for looking into it. I think better i create a new PR to avoid any confusion.

**Pull request closed without merging**
