### PR TITLE
[8.0][FIX][website_blog_share] Fixed Code / Broken travis build on linting

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Fixed Issue https://github.com/OCA/website/issues/518

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@simahawk Could you please review it?

**Comment by simahawk** [comment]
@nikul-serpentcs looks good but there are many errors like that ;)
Check this pls https://travis-ci.org/OCA/website/jobs/396024366

**Comment by nikul-serpentcs** [comment]
@simahawk  Resolved it, But If Travis start then I will check.

**Comment by nikul-serpentcs** [comment]
@simahawk Travis broken another module, Our module safely run.

**Comment by rafaelbn** [comment]
Travis is still :red_circle: Thanks a lot for your efforts!

**Comment by nikul-serpentcs** [comment]
@rafaelbn Thank You,
here  #518 issue is fixed but Other module get's Error.

CC @simahawk

**Comment by nikul-serpentcs** [comment]
@simahawk @rafaelbn Travis Done  

test_flake8 = https://travis-ci.org/OCA/website/jobs/438551787#L1988
test_pylint = https://travis-ci.org/OCA/website/jobs/438551787#L1989

**Review by simahawk — APPROVED** [review]
LG. Tests errors are un-related.
Thanks @nikul-serpentcs

**Comment by simahawk** [comment]
REMINDER: must squash before merge.

IMO we can merge this as it's going to fix the lint check.

I'll create a new ticket for the other error.

**Pull request merged**
