### PR TITLE
[IMP] website_logo multi-website support

### PR DESCRIPTION
**Pull request by antespi**
This improvement add:
- Support for multi-website.
- Configure logo in website settings instead of company configuration tab
- If no logo defined, then a transparent image is shown, allowing to not show logo in one website, even "Show logo" option is actived
- Migration script from 8.0.1.0.0

### CODE REVIEW

**Comment by rafaelbn** [comment]
Travis fails

**Comment by antespi** [comment]
@rafaelbn Travis is green now :smile:

**Comment by rafaelbn** [comment]
Thanks! tested :+1: 

@moylop260 @eLBati  maybe you are interested

**Comment by dgzurita** [comment]
Tested in runbot.

Can't save the logo image in Settings.

Thanks @antespi

**Comment by janetrp** [comment]
logo is not appearing when applying the changes and uploading a 180x50 image.

**Comment by antespi** [comment]
@rafabn, @janetrp and @dgzurita you are all right. All fields in `website.config.settings` must be related to website_id. Fixed, I hope all is working well.
Thanks for your review

**Comment by oscarolar** [comment]
Tested in Runbot :+1:

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Pull request merged**
