### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by PRESIDENT-caris**

### CODE REVIEW

**Comment by PRESIDENT-caris** [comment]
I AM NOT A SPAMMER DUDE ,PLZZ ACCEPT IT @pedrobaeza

**Comment by PRESIDENT-caris** [comment]
SIR!!! I AM NOT A SPAMER :'(

**Comment by pedrobaeza** [comment]
Yes, you are:

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by PRESIDENT-caris** [comment]
A YOUTUBER TOLD ME TWO DO THAT AND IAM NEW IN THIS SO I GOT CONFUSED @pedrobaeza

**Comment by PRESIDENT-caris** [comment]
*TO ,SORRY @pedrobaeza

**Comment by PRESIDENT-caris** [comment]
I CAN CHANGE ITS NAME TO UPDATED DOCS

**Comment by PRESIDENT-caris** [comment]
@pedrobaeza

**Comment by PRESIDENT-caris** [comment]
@pedrobaeza  PLZZ REPLY

**Comment by pedrobaeza** [comment]
https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama

Stop spamming now. This is not a real contribution.

**Comment by PRESIDENT-caris** [comment]
FOR THE FIRST TIME I GOT THIS TYPE OF BEHAVIOUR :'(

**Comment by PRESIDENT-caris** [comment]
SORRY SIR !!

**Comment by PRESIDENT-caris** [comment]
BUT I HAVE NO INTENSION TO DO THAT @pedrobaeza

**Comment by PRESIDENT-caris** [comment]
I YOU NEED A VERIFICATION THEN I AM A YOUTUBER FROM INDIA NAME PRESIDENT_CARIS @pedrobaeza

**Pull request closed without merging**
