### PR TITLE
[MIG][17.0] website_cookiebot

### PR DESCRIPTION
**Pull request by adriresu**
Standard migration

### CODE REVIEW

**Comment by adriresu** [comment]
Please @dalonsod, can you check It?

**Comment by dalonsod** [comment]
There's still a line for res.config.settings not covered by tests, could you check and add pending test for `cookiebot_enabled` field change?

image

**Comment by adriresu** [comment]
> There's still a line for res.config.settings not covered by tests, could you check and add pending test for `cookiebot_enabled` field change?
> 
> image

Test added and ready to check.

**Review by dalonsod — APPROVED** [review]
:+1: Please clean commit history as described at https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Comment by adriresu** [comment]
> 👍 Please clean commit history as described at https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

This is my first time merging commits in a OCA repository, but I believe I have merged the corresponding commits correctly. However, some of the commits cause issues when their order is changed for merging as It is mencioned in the documentation.
Hope It is ok.

**Comment by chienandalu** [comment]
Hi, could you include https://github.com/OCA/website/pull/1055

**Comment by Anxo82** [comment]
Done! Review please @chienandalu @dalonsod 
Thanks

**Review by chienandalu — APPROVED** [review]
Looks good. Thanks!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
