### PR TITLE
[15.0][ADD]website_sale_stock_notification

### PR DESCRIPTION
**Pull request by dsolanki-initos**
@jans23 FYI
Test is failed from other module

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
@Tardo Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@joao-p-marques Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@chienandalu Can you please review this PR?

**Comment by chienandalu** [comment]
No, sorry

**Review by ikapasi-initos — APPROVED** [review]
Code Review and functional test.
LGTM

**Comment by dsolanki-initos** [comment]
@HviorForgeFlow could you please review this PR?

**Review by tarteo — COMMENTED** [review]
Is this module the same? https://github.com/OCA/e-commerce/tree/14.0/website_sale_stock_available

**Comment by dsolanki-initos** [comment]
> Is this module the same? https://github.com/OCA/e-commerce/tree/14.0/website_sale_stock_available

No, Both are different, Can you please code review and approve this PR?

**Comment by jans23** [comment]
> Is this module the same? https://github.com/OCA/e-commerce/tree/14.0/website_sale_stock_available

Our module adds a new option "show inventory below a threshold, sell regardless and show product-specific notification for empty stock"

**Comment by pedrobaeza** [comment]
This should go to OCA/e-commerce. Check existing addons https://github.com/OCA/e-commerce/tree/13.0/website_sale_stock_force_block and https://github.com/OCA/e-commerce/tree/13.0/website_sale_stock_force_block

**Comment by dsolanki-initos** [comment]
> This should go to OCA/e-commerce. Check existing addons https://github.com/OCA/e-commerce/tree/13.0/website_sale_stock_force_block and https://github.com/OCA/e-commerce/tree/13.0/website_sale_stock_force_block

@pedrobaeza , Closing this PR as this module is moved to OCA/e-commerce, PR: https://github.com/OCA/e-commerce/pull/728

**Pull request closed without merging**
