### PR TITLE
[17.0][MIG] website_require_login: Migration to 17.0

### PR DESCRIPTION
**Pull request by vvro**
website_require_login module works as is from version 16.0, just updated the version to 17.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Now formally seems OK. Thanks.

/ocabot migration website_require_login

**Comment by pedrobaeza** [comment]
Ouch, there's another PR already.

**Comment by vvro** [comment]
It seems already fixed, but pending for almost half year. How should we proceed in this case? @pedrobaeza

**Comment by pedrobaeza** [comment]
You should review it https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#L1345

**Pull request closed without merging**
