### PR TITLE
[MIG][9.0] website_logo ported to 9.0

### PR DESCRIPTION
**Pull request by StephanRozendaal**
Changes include:
- update version number
- make module installable
- In company_view use an xpath expression to add logo configuration to
  company view.

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested, thanks!

**Review by eLBati — CHANGES_REQUESTED** [review]
Looking at the diff with version 8
http://pastebin.com/fhYi2scm
it seems last changes are missing.

Please follow the procedure described at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#howto

**Comment by oscarolar** [comment]
👍

**Comment by rafaelbn** [comment]
Please @StephanRozendaal review comment from @eLBati , thanks!

**Comment by pedrobaeza** [comment]
Why do you close this? You can add missing commits on top of (or replacing) this branch

**Comment by StephanRozendaal** [comment]
Sorry, I was messing around. Commits are fixed now.

**Review by pedrobaeza — APPROVED** [review]
It would be great if you squash all the "OCA Transbot..." commits together along with the "Remove en.po", because they are not relevant as separated ones

**Comment by StephanRozendaal** [comment]
@pedrobaeza squash the commits like this?

**Comment by pedrobaeza** [comment]
Yeah, perfect, let me check the CLA and let CIs to finish and I'll merge.

**Comment by pedrobaeza** [comment]
Hi, Stephan, I'm checking the CLA and I can't find it. Did you sign it and send it to cla@odoo-community.org? If yes, can you please resend it?

**Comment by StephanRozendaal** [comment]
@pedrobaeza I have not signed it yet, sorry. This is my first PR for OCA code.
If you need it I can sign and send it in 24 hours.

**Comment by pedrobaeza** [comment]
Yes, please, it's a requisite to merge this. Please ping me in this PR when done, and congratulations for your first contribution to OCA!!

**Comment by StephanRozendaal** [comment]
@pedrobaeza I just sent an email to the CLA address.

**Comment by lasley** [comment]
Hi @StephanRozendaal - thanks for the contribution. I have an open PR for this #192 that I have somewhat abandoned. It contains a lot of new tests that should be integrated here though IMO. You can probably get them easily with a cherry-pick of c1c9d53555745c8117be46b5dafeabb90b8c386d

**Comment by pedrobaeza** [comment]
CLA checked. Waiting for the tests mentioned by Lasley.

**Comment by pedrobaeza** [comment]
You should change last commit author to give credentials to @lasley. When done, I'll merge.

**Comment by StephanRozendaal** [comment]
@pedrobaeza Ah you're right! I fixed it.

**Review by lasley — APPROVED** [review]
👍  from me, assuming the tests pass 😆 

Thanks again for the contribution @StephanRozendaal

**Pull request merged**
