### PR TITLE
[17.0][MIG] website_form_require_legal: Migration to 17.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
Standard MIgration to 17.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do the changes of the version in the migration commit, not in the pre-commit one

**Comment by NICO-SOLUTIONS** [comment]
> Please do the changes of the version in the migration commit, not in the pre-commit one

@pedrobaeza  Yes of Course. Sorry and thanks for the hint! Done.

**Review by Anxo82 — APPROVED** [review]
Functionally test :+1:

**Review by ChristianSantamaria — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
Can you please rebase to get a functional runboat?

**Comment by NICO-SOLUTIONS** [comment]
> Can you please rebase to get a functional runboat?

@pedrobaeza done

**Review by pedrobaeza — APPROVED** [review]
Functionally tested in runboat

/ocabot merge nobump

**Pull request merged**
