### PR TITLE
[14.0][MIG] website_cookiefirst: Cookiefirst integration

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration to 14.0 from https://github.com/OCA/website/pull/815

### CODE REVIEW

**Review by bosd — CHANGES_REQUESTED** [review]
Functional review
No cookie popup on Firefox and Chrome browser

**Comment by bosd** [comment]
It was not very clear that the icon was a cookie. Maybe this is an interesting suggestion.

icon

**Comment by ioans73** [comment]
@bosd I understand that before testing it, the API key obtained in the Cookiefirst platform has been configured, right?
If so, has the URL of the instance generated in runbot been enabled in the Cookiefirst API settings?

**Comment by bosd** [comment]
> I understand that before testing it, the API key obtained in the Cookiefirst platform has been configured, right?
If so, has the URL of the instance generated in runbot been enabled in the Cookiefirst API settings?

Well, I did'nt do a proper functional review. As I did not input an Cookiefirst API key.
The other review of V13 was not a proper review as well, Turns out the regular cookie module was installed, which is the one showed on the website.

I will approve this, so it will not block this PR. Maybe someone can do a proper functional review.

**Review by bosd — APPROVED** [review]

**Comment by ioans73** [comment]
I have made a few small changes

website_cookiefirst_14

**Review by fuentes73 — APPROVED** [review]

**Review by claudiagn — APPROVED** [review]
functional review ok! 👍

**Review by lmmar-ic — APPROVED** [review]
functional review ok.

**Review by Abranes — APPROVED** [review]

**Pull request merged**
