### PR TITLE
[FIX] website_slides: Add fetch timeout

### PR DESCRIPTION
**Pull request by yajo**
This makes you actually able to install the module with demo data and unplugged from network. Otherwise, it's impossible.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this will likely happen in future versions in Odoo core, isn't it?

**Comment by yajo** [comment]
Indeed it has the same problem, but it's hitting me here right now...

**Comment by pedrobaeza** [comment]
Well, we are going to migrate in 2 months, so we might find a definitive solution.

**Comment by yajo** [comment]
I opened https://github.com/OCA/OCB/pull/808 and https://github.com/odoo/odoo/pull/28098 to provide the definitive solution, and travis :x: is not related.

**Review by rafaelbn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Main branch is red, but I'm going to merge this old one for having it.

**Pull request merged**
