### PR TITLE
[14.0][IMP] website_plausible: Added docs for configuration if Plausible is self-hosted

### PR DESCRIPTION
**Pull request by wytzejan**

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Indeed, thanks

**Comment by chienandalu** [comment]
Can you forward port to v15?

**Comment by wytzejan** [comment]
Sure, I will do that within the next days.

**Comment by wytzejan** [comment]
@chienandalu hereby: https://github.com/OCA/website/pull/992

**Pull request merged**
