### PR TITLE
[16.0][ADD] website_analytics_umami

### PR DESCRIPTION
**Pull request by yibudak**
Umami is a simple, fast, privacy-focused alternative to Google Analytics. (https://github.com/umami-software/umami). It's a new project, but it is growing very fast. Assuming that Odoo 16 is the latest version, I wanted to add the Umami module to the website repo with this PR.

image

### CODE REVIEW

**Review by tarteo — APPROVED** [review]
Awesome! LGTM

**Comment by yibudak** [comment]
Umami grows continuously, is there any chance to merge? @pedrobaeza

**Comment by pedrobaeza** [comment]
Please review other PRs and ask in exchange that they review yours. You need 2 positive reviews, and one from a PSC for this being merged.

https://odoo-community.org/resources/review
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Comment by yibudak** [comment]
> Please review other PRs and ask in exchange that they review yours. You need 2 positive reviews, and one from a PSC for this being merged.
> 
> https://odoo-community.org/resources/review https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

Thanks for your quick answer. I will work on it.

**Comment by pedrobaeza** [comment]
For this one, please squash all the commits into one, as they don't bring added value to be separated.

**Comment by yibudak** [comment]
> For this one, please squash all the commits into one, as they don't bring added value to be separated.

Done. Thank you.

**Pull request closed without merging**
