### PR TITLE
[FIX][website_seo_redirection] Make the promote panel work again

### PR DESCRIPTION
**Pull request by yajo**
SEO features were not visible, and pressing on save button was failing always.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is Travis error the usual problem?

**Review by pedrobaeza — APPROVED** [review]
Code review

**Comment by yajo** [comment]
[Indeed](https://travis-ci.org/OCA/website/jobs/262143911#L1893-L1901), it's https://github.com/OCA/maintainer-quality-tools/issues/471 yet again.

**Review by lasley — APPROVED** [review]
Code 👍 

How the hell does this SAAS/Compass issue keep striking back

**Comment by pedrobaeza** [comment]
Thanks to #375, and after rebasing, this is green, so I merge.

**Pull request merged**
