### PR TITLE
[16.0][MIG] website_form_require_legal: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT44376

@chienandalu @CarlosRoca13 please review

### CODE REVIEW

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
Something is wrong...

error_include

**Comment by pilarvargas-tecnativa** [comment]
> Something is wrong...

I tried again locally, it should no longer happen

**Comment by CarlosRoca13** [comment]
I have found another error: error_classlist

**Comment by pilarvargas-tecnativa** [comment]
> I have found another error:

is a error in the website_crm_privacy_policy module, it is corrected at https://github.com/OCA/website/pull/1014

**Comment by pilarvargas-tecnativa** [comment]
@CarlosRoca13 The error you were experiencing in runbot in the contact form is already fixed in the other module, however the functionality test has to be done by inserting a new form block as the other module already has the contact form customised and only allows editing the link. In local tests where the two modules do not coexist, the functionality is also applied to the contact form, so to check that it really works you would have to do it without the other module marked as "deprecated" installed.

**Review by AungKoKoLin1997 — APPROVED** [review]
Functional Review: LGTM

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
