### PR TITLE
website sale customer interface

### PR DESCRIPTION
**Pull request by simahawk**
This PR  adds a module `website_sale_customer` that adds proper customer views to your shop.
It starts as a port of the improvements done on odoo 9 but it gives you more.

The customer has 2 new items in his/her personal menu: `my account` and `my orders`.

The 1st one allows the customer to edit his/her data with a form that validates the inputs and that ease overrides of validation and other stuff.

The second view allows the customer to view his/her orders without having to deal w/ odoo backend.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why not call it _website_customer_portal_?

**Comment by simahawk** [comment]
because it's just for a customer of an e-commerce :)

**Comment by pedrobaeza** [comment]
You can also use it if you want for all kind of orders. Anyways, the proposed name also fits for that scenario.

**Comment by simahawk** [comment]
yeah, as long as you have a "website" and you "sale" things to a "customer", should be good ;)

So, what's missing here for getting merged? The errors I see are just warnings.
Do you prefer the routes to be `/web/*` instead of `/shop/*`?

**Comment by pedrobaeza** [comment]
You should check why Travis and runbot give errors and fix them. Then, at least 2 person must review and approve your PR in order to be merged

**Comment by pedrobaeza** [comment]
I'm seeing now that this module gets deprecated with the use of https://github.com/OCA/website/tree/8.0/website_portal_sale

**Comment by rafaelbn** [comment]
Hi @simahawk , sorry for this PR. Are you agree to close this PR? Let me know please. Thanks!

**Comment by simahawk** [comment]
@rafaelbn yes, go ahead pls. I don't know how it works now (not tried yet) but we could rescue the code if needed in the future.

**Pull request closed without merging**
