### PR TITLE
[14.0][ADD] website_plausible

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This module allows to configure your odoo website to connect with Plausible.

The addon is based on the Odoo 16 feature.

@ForgeFlow

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you avoid plurals in module name? It can be `website_plausible` for example.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza sure, done!

**Comment by ElmerGForgeFlow** [comment]
LGTM!

**Review by ElmerGForgeFlow — APPROVED** [review]
LGTM!

**Review by etobella — APPROVED** [review]
Good for me.

As it is a backport from an official CE module from Odoo, can you add them as authors. Also, it is a port of an odoo module, so it is not under OCA CLA. I would add:

```
This module is a move from Odoo SA code and as such, it is not included in the
OCA CLA. That means we do not have a copy of the copyright on it like all other
OCA modules.
```

**Comment by LoisRForgeFlow** [comment]
@etobella You are right, it is corrected now.

Thanks!

**Comment by LoisRForgeFlow** [comment]
@etobella could you try to merge again?

**Pull request merged**
