### PR TITLE
[FIX][9.0] Fixing ssl break and redirect for multilanguage websites

### PR DESCRIPTION
**Pull request by lasley**
v9 forward port of @PCatinean's #276

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
As this has been already reviewed in v8, we can fast-track it

**Comment by pedrobaeza** [comment]
Wait, can you check Travis?

**Comment by lasley** [comment]
Interesting, Travis is complaining regarding SASS execution:

```
ERROR openerp_test openerp.addons.base.ir.ir_qweb: Could not execute command 'sass'
```

I haven't seen something this broken in a while, so I'm hoping maybe a dependency just didn't download or something. I restarted the Travis builds on an off-hope it will resolve itself & will come back to this later today.

**Comment by lasley** [comment]
Merging on previous approval, and now 🍏  CIs from rebase on 9

**Pull request merged**
