### PR TITLE
[12.0][MIG] website_adv_image_optimization: Migration to 12.0

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa TT23347

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
It doesn't work with png's. Maybe just add to roadmap?

**Comment by Tardo** [comment]
@chienandalu work's to me, this module doesn't accept pictures from URL's

Can you share a picture or video with the issue? thx!

**Comment by chienandalu** [comment]
STR:

- Uploaded a png
- Tried to resize it (no error)
- Place it in the page
- Inspect image properties.
- The size is still the original.

With jpg goes fine

**Comment by Tardo** [comment]
@chienandalu I can't reproduce it :/
avd_image

**Review by chienandalu — APPROVED** [review]
Ok then :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by sergio-teruel** [comment]
@Tardo in bowser I obtain an error when do double click to edit image...
Selección_634

**Comment by pedrobaeza** [comment]
Aborted then the merge

**Comment by Tardo** [comment]
Tested on runbot and worked as expected: http://3417613-711-736f41.runbot1.odoo-community.org/?fw=1#scrollTop=0

**Pull request merged**
