### PR TITLE
Support pages and ticket system based on 

### PR DESCRIPTION
**Pull request by marcos-mendez**
This module is from https://apps.odoo.com/apps/modules/12.0/website_support/

It is under LGPLv3 and has more than 15000 Downloads. It is an integration to support pages and ticketing system on the website

We currently use it on our operation and we would like to it be maintained and integrated to OCA.

This is my first pull request, i don't know if this is allowed or not

I don't have express autorization from the author but as it is LGPLv3 i think it is compatible with the other GNU licenses i don't know im just trying to contribute

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can't put here any module without the CLA signed by original authors, and you must respect commit history. See OCA/helpdesk for a good alternative already existing.

See https://odoo-community.org/page/cla for more information.

**Comment by pedrobaeza** [comment]
@gurneyalex it seems the CLA bot is not working.

**Comment by marcos-mendez** [comment]
> You can't put here any module without the CLA signed by original authors, and you must respect commit history. See OCA/helpdesk for a good alternative already existing.
> 
> See https://odoo-community.org/page/cla for more information.

@pedrobaeza Do you recommend anythong for the Help Pages from the module i commented before. Sorry I didn't know about the CLA

**Comment by pedrobaeza** [comment]
`website_slides` from v13

**Pull request closed without merging**
