### PR TITLE
[16.0][MIG] website_cookiebot: Migration to 16.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
Standard migration

### CODE REVIEW

**Comment by NICO-SOLUTIONS** [comment]
can anybody assist in understanding the failing tests?!

**Comment by pedrobaeza** [comment]
Install and run pre-commit locally, that will reformat your code, or change this manually:

Selección_055

**Comment by NICO-SOLUTIONS** [comment]
Many thanks pedro!
pre-commit was installed but i probably just forget something... 
I dont know if the way of commiting that step is correct or rather meets the foreseen workflow.

How about the codecov tests? do i need to take these into account?

**Comment by NICO-SOLUTIONS** [comment]
ok sorry for the noise guys.
just tried to get rid of the commits in between but i think i need some hint what i´ve done worng.

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by NICO-SOLUTIONS** [comment]
closed due to merge in #1006

**Pull request closed without merging**
