### PR TITLE
[12.0][MIG] website_portal_contact

### PR DESCRIPTION
**Pull request by SirTakobi**
Superseding https://github.com/OCA/website/pull/840

Added history with format patch, plus some improvement (see commits) that ideally should go in the migration commit.
I'm keeping the new edits in dedicated commits in order to preserve authorship in existing commits.

### CODE REVIEW

**Comment by SirTakobi** [comment]
> Hey @SirTakobi, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet. You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla Here is a list of the users:
> 
> * Jairo Llopis [jairo.llopis@tecnativa.com](mailto:jairo.llopis@tecnativa.com) (no github login found)
> * Mathieu Benoit [mathieu.benoit@mathben.tech](mailto:mathieu.benoit@mathben.tech) (no github login found)
> 
> Appreciation of efforts, OCA CLAbot

@Yajo @mathben can I have the email linked to your accounts so that I can set it inside your commits?
Otherwise just point me to one of your commits where the github user is recognized and I'll get the email from there.
Thanks!

**Comment by mathben** [comment]
@SirTakobi I update my github settings with the email mathieu.benoit@mathben.tech
Is it working?
Thanks

**Comment by SirTakobi** [comment]
> @SirTakobi I update my github settings with the email [mathieu.benoit@mathben.tech](mailto:mathieu.benoit@mathben.tech) Is it working? Thanks

Yes, now your commits in this PR show the github user too:
image

**Comment by yajo** [comment]
I think that's a bug in the bot and we can just ignore it. See https://github.com/OCA/oca-github-bot/issues/209.

**Review by eLBati — CHANGES_REQUESTED** [review]
portalcontacts

**Review by eLBati — APPROVED** [review]
thanks

**Review by tarteo — CHANGES_REQUESTED** [review]
I tried to install it on my local machine but I get this error:
```
Exception: Module loading website_portal_contact failed: file website_portal_contact/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'product.model_product_pricelist' in field 'Object'
Missing required value for the field 'Object' (model_id)
```

I guess a dependency is missing

**Comment by SirTakobi** [comment]
> I tried to install it on my local machine but I get this error:
> 
> ```
> Exception: Module loading website_portal_contact failed: file website_portal_contact/security/ir.model.access.csv could not be processed:
>  No matching record found for external id 'product.model_product_pricelist' in field 'Object'
> Missing required value for the field 'Object' (model_id)
> ```
> 
> I guess a dependency is missing

Thanks for having a look, you are right it was missing the dependency from `product`, now I have added it.

EDIT: I know the new dependency might not fit in this module that ideally should only depend on `website` and `portal`, another possible way to fix it would be to create a bridge module for `product` and `website_portal_contact`

**Review by eLBati — APPROVED** [review]
LGTM

**Review by tarteo — APPROVED** [review]
Thanks!

**Review by mrcast — APPROVED** [review]
Functional test ok!

**Comment by SirTakobi** [comment]
> /ocabot merge nobump

@tarteo thanks for trying :smile: 

Maybe someone of @OCA/website-maintainers can have a look?

**Comment by SirTakobi** [comment]
@OCA/website-maintainers can someone have a look? Thanks!

**Comment by hbrunn** [comment]
could you squash all your migration commits?

**Comment by SirTakobi** [comment]
> could you squash all your migration commits?

I have squashed most of the commits; I have kept a few commits separated because they are dedicated to specific improvements, could you please check if it looks better now?

**Comment by hbrunn** [comment]
thanks
/ocabot merge nobump

**Pull request merged**
