### PR TITLE
[FIX] Remove unpublished departments from the breadcrumb

### PR DESCRIPTION
**Pull request by lmignon**
to avoid AccessDenied for visitors

### CODE REVIEW

**Comment by rafaelbn** [comment]
In which URL it's the issue?

**Comment by lmignon** [comment]
@rafaelbn 
Hzre it's the steps to reproduce the bug without the patch:
- Create department DEP1
- Create department DEP11 child of DEP1
  In a website page create a link to the page generated for DEP11 (the url starts with /departments/...)
- Publish the page of the department DEP11
- as an anonymous visitor, try to access to the  page by clikcink on the new link.
  Current behaviour: AccessDenied
  Expected behaviour: The page is displayed and the parent department is not displayed in the breadcrumb since it's not published.

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by lmignon** [comment]
rebased after merge of #97

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Comment by lmignon** [comment]
@pedrobaeza @hbrunn I think that this one can be merged.

**Comment by lmignon** [comment]
Thank you @StefanRijnhart

**Pull request merged**
