### PR TITLE
[IMP] website_event_register_free: Some hooks for inheriting the module

### PR DESCRIPTION
**Pull request by pedrobaeza**
This way, life would be easier for adding some customizations to this module :wink:

### CODE REVIEW

**Comment by antespi** [comment]
:+1:

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@hbrunn, I have used it succesfully in two projects with these hooks. Can you review it and merge it?

**Comment by hbrunn** [comment]
./website_event_register_free/model/event_registration.py:39:1: W391 blank line at end of file
./website_event_register_free/controllers/website_event.py:21:1: F401 'fields' imported but unused

**Comment by hbrunn** [comment]
rest looks good to me

**Comment by pedrobaeza** [comment]
I didn't activate pre-commit in this repo...

Now it's done. Thanks for the review.

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
