### PR TITLE
[12.0][MIG] website_snippet_anchor

### PR DESCRIPTION
**Pull request by yajo**
- Remove the feature of splitting and rejoining the given URL.
- Replace it by helpful text in the right context.
- Make JS linter happy.
- Update docs.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@ernestotejeda please review

**Review by pedrobaeza — APPROVED** [review]

**Comment by ernestotejeda** [comment]
I don't know if I'm doing something wrong, but it doesn't work for me, this is a gif that I did when I was trying on runbot

Peek 22-04-2019 09-40

**Comment by yajo** [comment]
Let's see now.

**Review by ernestotejeda — APPROVED** [review]

**Comment by yajo** [comment]
I just noticed that in v13 this module will not be needed: https://github.com/odoo/odoo/commit/59cc261448b67c424051a623c5c8d76ddd20aa71

**Comment by pedrobaeza** [comment]
Added information in b91f2e9b88dd70b9d6afe8738dfc06b6a0a6cab7

**Pull request merged**
