### PR TITLE
[11.0][ADD] website_snippet_preset

### PR DESCRIPTION
**Pull request by tarteo**
This module allows the user to save and restore presets of snippets.

### CODE REVIEW

**Comment by tarteo** [comment]
The travis fail doens't seem to be related to this module.

**Comment by pedrobaeza** [comment]
Main branch is green. I have launched a rebuild of main branch to see if it's something changed upstream.

**Comment by pedrobaeza** [comment]
Indeed, it's not caused by this PR. I'm writing an issue.

**Review by rgarnau — APPROVED** [review]
LGTM :+1:

**Review by njeudy — APPROVED** [review]
LGTM 👍

**Pull request merged**
