### PR TITLE
[9.0][website_portal_sale_v10] Backport sale website portal from master.

### PR DESCRIPTION
**Pull request by yajo**
See rationale on https://github.com/OCA/website/pull/204.

This module includes the sale components for the website portal.

This is **not** compatible with current v9 implementation of `website_portal`.

Please somebody mark as WIP until these are merged:
- [x] #204 
- [x] #205 
- [x] https://github.com/odoo/odoo/pull/12284 (I will have to backport this once they merge it and forwardport it to master).

@Tecnativa.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Yajo all dependencies are now merged, so please rebase what you need and check CIs status for starting the review

**Comment by yajo** [comment]
This is now ready to review, coverage should be improved upstream instead.

**Comment by rafaelbn** [comment]
Rebuilding for testing

**Review by pedrobaeza — APPROVED** [review]
This one is correct since long ago, so I merge.

**Pull request merged**
