### PR TITLE
[13.0] website_crm_privacy_policy bug xpath #803

### PR DESCRIPTION
**Pull request by vanderperre**
installation : XML parser don't find parent

suggestion

replace in templates/contactus.xml

expr="//form/div/div/span[@id='o_website_form_result']/../.."
by
expr="//form//div/div/span[@id='o_website_form_result']/../.."

### CODE REVIEW

**Review by wytzejan — COMMENTED** [review]
I don't think that it is really necessary. In runbot it matches the exact div with only one slash:
image

Maybe you have a custom form layout somewhere that causes the 'XML parser don't find parent' error?

**Comment by vanderperre** [comment]
> I don't think that it is really necessary. In runbot it matches the exact div with only one slash:
> image
> 
> Maybe you have a custom form layout somewhere that causes the 'XML parser don't find parent' error?

ok BUT :

Ideally, it would simply be necessary to match the identifier but referencing to the two division is not useless
It's hard to explain to the client that they can't include a super division inside the form ...

**Comment by wytzejan** [comment]
I understand. I'm curious about why you would like to include a super division inside the form. But anyway, your requested changes does not break anything so I will approve :)

And may I ask you to review my merge request (#801)? I would very much like that.

**Review by wytzejan — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
