### PR TITLE
[9.0][website_blog_excerpt_img] Migrate, LGPL.

### PR DESCRIPTION
**Pull request by yajo**
Relicensed, migrated, transbot squashed.

@Tecnativa

### CODE REVIEW

**Review by rafaelbn — CHANGES_REQUESTED** [review]
- Go to Runbot
- Go to blog without login
- 500: Internal Server Error

Please check

**Comment by yajo** [comment]
Rebased, squashed, added tests, and fixed problem.

**Comment by yajo** [comment]
Travis seems affected too by https://github.com/OCA/server-tools/pull/666

**Comment by pedrobaeza** [comment]
Can you please rebase?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@rafaelbn please re-review this

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
