### PR TITLE
[12.0][MIG] website_anchor_smooth_scroll

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
ping: @Yajo

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you put README by fragments?

**Comment by MiquelRForgeFlow** [comment]
I have put the `readme` folder with the fragments. After merge, the readme file will be autogenerated. Why I don't generate it? Because last time I tried, I wasn't able.

**Review by pedrobaeza — APPROVED** [review]
OK, let's wait for the bot to do it.

**Pull request merged**
