### PR TITLE
[12.0][ADD] website_google_analytics_anonymize_ip

### PR DESCRIPTION
**Pull request by wytzejan**
This module adds the ability to enable the Google Analytics IP Anonymization feature.
The feature adds 'ga('set', 'anonymizeIp', true);' to the tracking-code script once enabled.

### CODE REVIEW

**Review by gfcapalbo — APPROVED** [review]
:+1:

**Comment by ioans73** [comment]
Code review

**Review by ioans73 — APPROVED** [review]

**Comment by wytzejan** [comment]
Hi @pedrobaeza! This one is ready to be merged. Are you willing to do that for me? I can review something for you if you would like!

**Comment by pedrobaeza** [comment]
@wytzejan if I ask reviews in exchange is not for me, but for entire community, and yes, you should do it if you can.

Merging this one due to the existing approves:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
There are several errors in the branch, like:
```
website_google_analytics_anonymize_ip/models/res_config_settings.py:4:1: F401 'odoo._' imported but unused
website_google_analytics_anonymize_ip/models/res_config_settings.py:4:1: F401 'odoo.api' imported but unused
website_google_analytics_anonymize_ip/models/website.py:4:1: F401 'odoo._' imported but unused
website_google_analytics_anonymize_ip/models/website.py:4:1: F401 'odoo.api' imported but unused
```

Please rebase and check them.

**Pull request closed without merging**
