### PR TITLE
Add module website_signup_legal_page_required.

### PR DESCRIPTION
**Pull request by yajo**
Force accepting legal terms before opening user account.

cc @rafaelbn.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please
- Change module name to website_signup_legal_page_required please. This module apply only in that screen.
- Please translate to English the notice text then check-box is unselected:
  

Thanks

**Comment by dgzurita** [comment]
500 Internal Server Error after signup

**Comment by yajo** [comment]
@rafaelbn that message is from your browser.

**Comment by yajo** [comment]
Module renamed.

@dgzurita it must be a runbot error, local tests work fine.

**Comment by yajo** [comment]
Relevant lines from Travis:

```
2015-10-07 14:34:03,938 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: Tour 'event_buy_tickets' is running (Demo User)
2015-10-07 14:34:03,940 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
2015-10-07 14:34:03,950 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: Cycling. Can't reach the next step
2015-10-07 14:34:03,950 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  tour: event_buy_tickets
2015-10-07 14:34:03,951 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  step: 8: 'select payment'
2015-10-07 14:34:03,951 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  href: http://localhost:8069/shop/confirm_order
2015-10-07 14:34:03,952 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  referrer: http://localhost:8069/shop/confirm_order
2015-10-07 14:34:03,952 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  element: false
2015-10-07 14:34:03,952 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  waitNot: true
2015-10-07 14:34:03,952 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  waitFor: true
2015-10-07 14:34:03,953 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  localStorage: {"tour":"{\"id\":\"event_buy_tickets\",\"mode\":\"test\",\"step_id\":7,\"time\":1444228434364,\"number\":4,\"wait\":0}"}
[...]
2015-10-07 14:34:04,786 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs:  (Demo User)
2015-10-07 14:34:04,786 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: Tour reset
2015-10-07 14:34:04,786 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: Tour 'event_buy_tickets' finish: error
2015-10-07 14:34:04,786 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: error
2015-10-07 14:34:04,794 22852 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantom_run execution finished
2015-10-07 14:34:04,814 22852 [1;31m[1;49mERROR[0m openerp_test openerp.addons.website_event_sale.tests.test_ui: FAIL
```

Seems to be an error when testing the website_event_sale workflow. These tests work fine locally, could it be a Travis error?

**Comment by janetrp** [comment]
The check box still have the message in spanish.
Internal server error when ok in sign up.
2015-10-22 16_18_38-clipboard

**Comment by yajo** [comment]
Please read above comments.

**Comment by yajo** [comment]
Found error, it's in settings. Please read updated configuration section in README.

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Comment by dgzurita** [comment]
Tested in runbot :+1:

**Comment by carlosdauden** [comment]
Travis error website_sale tests.
:+1:

**Comment by rafaelbn** [comment]
cc @pedrobaeza codul you tell us why travis fails?

**Comment by rafaelbn** [comment]
@carlos-incaser Do Travis errors come from module website_sale which is already merged in OCA?

**Comment by rafaelbn** [comment]
cc @pedrobaeza could you check travis errors? you commented here https://github.com/OCA/website/pull/68#issuecomment-131192089

**Comment by janetrp** [comment]
Tested in Chrome and following your directions in Read me and it works fine :+1:

**Comment by yajo** [comment]
Bug detected: getting checkbox also in reset password form. Let me fix before continuing.

**Comment by yajo** [comment]
cc @rafaelbn

**Comment by yajo** [comment]
That should be fixed now.

**Comment by yajo** [comment]
IMHO this has a good collection of :+1:

**Pull request merged**
