### PR TITLE
Upgrade website_legal_page to 9.0

### PR DESCRIPTION
**Pull request by lasley**
I noticed a massive amount of changes on `website_cookie_notice` in the 8.0 branch while bringing forward to 9.0 for #193. This module is now a dependency for it, so I am upgrading it to 9.0 as well (after cherry picking the 8.0 changes)

### CODE REVIEW

**Comment by lasley** [comment]
Superseded by #106

**Comment by lasley** [comment]
This is more up to date than #106, and included cherry-picking to preserve the commit authors. I would say that this should be the PR for website_legal

**Comment by eLBati** [comment]
Thanks @lasley 
looking at the diff with 8.0
http://pastie.org/10809155
it seems some translations are missing

Please add them

**Comment by lasley** [comment]
Good catch, thanks @eLBati - I meant to pull them in manually after my cherry-picks, but then completely forgot

**Comment by eLBati** [comment]
LGTM :+1: thanks

**Comment by yajo** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

I merge, including some translations updates done in 8.0 meanwhile, and giving credits for example to @Yajo, that is not included in the README.

**Pull request merged**
