### PR TITLE
[MIG][10.0] website_seo_redirection

### PR DESCRIPTION
**Pull request by mobilizer**
Migration to version 10.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please integrate correctly the migration commit (not with a merge) and send the CLA.

**Comment by mobilizer** [comment]
@pedrobaeza The CLA was send today.

Concerning the failed tests: Is there any docs on changes in Odoo 10 Tour tests?

**Comment by pedrobaeza** [comment]
I'm afraid not. You have to dig into the error, see the code, mimic some things in Odoo codebase, and get to the green state.

**Comment by yajo** [comment]
Thanks for migrating, in v10 the tours have changed dramatically.

I have not digged into that yet, but best resources you have is [this slideshow](https://www.tecnativa.com/slides/slide/the-new-way-to-develop-automated-tests-beautiful-tours-36) until they document it as they promised.

**Comment by yajo** [comment]
Still ❌

**Comment by yajo** [comment]
Please review https://github.com/OCA/website/pull/297, not sure if you need that patch for v10.

**Review by thilina570 — CHANGES_REQUESTED** [review]
@ mobilizer 
I went throug your changes and get this error when I try to install the module on odoo 10. Can you please look at it.
 
Model not found: website.seo.redirection

Error context:
View `Website SEO Redirection Form`
[view_id: 328, xml_id: n/a, model: website.seo.redirection, parent_id: n/a]
None" while parsing /opt/odoo/odoo-10.0/addons/website_seo_redirection/views/website_seo_redirection_view.xml:7, near
<record id="website_seo_redirection_form_view" model="ir.ui.view">
    <field name="name">Website SEO Redirection Form</field>
    <field name="model">website.seo.redirection</field>
    <field name="arch" type="xml">
        <form>
            <sheet>
                <group>
                    <field name="origin"/>
                    <field name="destination"/>
                    <field name="relocate_controller"/>
                </group>
            </sheet>
        </form>
    </field>
</record>

**Comment by mobilizer** [comment]
@thilina570 Actually the migration is WIP. But installation should work on 10. 

Also there will be a merge of current 9.0 changes soon including the additions made in the _seoredirections 9.0 branch.

**Comment by yajo** [comment]
Marking as such then to avoid confusion.

**Comment by lasley** [comment]
Superseded with #329

**Pull request closed without merging**
