### PR TITLE
10.0 website multi theme fix data is not defined

### PR DESCRIPTION
**Pull request by yelizariev**
Depends on #441 

Fixes mistake in #430 

So, it's just another evidence that tests are useful thing, but I still have a [doubt](https://github.com/OCA/website/pull/430#issuecomment-372824306) how to do it in this case.

### CODE REVIEW

**Review by Railia — CHANGES_REQUESTED** [review]
When I set up the theme "Clean" for the 2nd website, using the "Reload theme" button, I get an error message

**Review by Railia — APPROVED** [review]
The previous check was incorrect. It was a problem with the database. After reinstalling the database, the module is working fine!

**Review by yajo — APPROVED** [review]
Keep in mind that, although the design of this addon is mostly OK, it's got some design flaws and is very *hacky*. It abuses many low-level things inside Odoo to make multi themes possible. With such properties, if you don't test these bugs, it's very likely that we'll have them in future versions...

I won't lock it for not having tests, but friend please think on that. :wink: 

About how to do them, basically you just have to do like always:

1. Create some data that hits the corner case.
2. Check that the method works.

- In some cases you might need to use an `HttpCase`
- In such cases you'll need to apply https://github.com/odoo/odoo/issues/12237#issuecomment-254781169 to acquire/release the same cursor that the http connections will use
- You might also need to use [mock](https://docs.python.org/3/library/unittest.mock.html) under some circumstances.

Oh, and rebase please!

**Comment by pedrobaeza** [comment]
Please solve conflicts. Are you going to try the tests?

**Comment by yelizariev** [comment]
I'll try to do some test. Probably just put fake data in ``converted_theme_addon`` field or try to find another solution

**Comment by yelizariev** [comment]
There is no coverage tool anymore?

I added some test. They are only for coverage without real checking

**Comment by yelizariev** [comment]
Ok, codecov is working and shows that the lines are covered

**Comment by pedrobaeza** [comment]
OK, thank you very much.

**Pull request merged**
