### PR TITLE
FIX website_event_register_free …

### PR DESCRIPTION
**Pull request by angelmoya**
…to allow register by public user on event without seat max

more info on issue #263

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please don't reformat all the code. Change only the corresponding line of the t-if.

**Comment by rafaelbn** [comment]
Please @angelmoya could you review this one, thanks!

cc @Yajo

**Comment by yajo** [comment]
@angelmoya does not answer, I fixed this myself.

**Comment by angelmoya** [comment]
Thanks @Yajo , and sorry

**Review by rafaelbn — APPROVED** [review]
👍

**Review by yajo — APPROVED** [review]

**Pull request merged**
