### PR TITLE
[15.0][ADD] website_mass_mailing_double_opt_in

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by tarteo** [comment]
@dsolanki-initos Thanks for your contribution! Can you please add the full comnit history. You can find instruction on how to do that here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#how-to

**Comment by tarteo** [comment]
@dsolanki-initos Thanks for your contribution! Can you please add the full comnit history. You can find instruction on how to do that here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#how-to

**Comment by tarteo** [comment]
Can you also add some tests, please.

**Comment by tarteo** [comment]
Can you also add some tests, please.

**Comment by dsolanki-initos** [comment]
> Can you also add some tests, please.

Sure i will add

**Comment by dsolanki-initos** [comment]
@antespi can you pleaser review this PR?

**Comment by dsolanki-initos** [comment]
@antespi can you please review this PR?

**Comment by dsolanki-initos** [comment]
@sergio-teruel Can you please review this PR?

**Comment by dsolanki-initos** [comment]
> Can you also add some tests, please.

I have added a test case

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional test.
LGTM

**Comment by dsolanki-initos** [comment]
@lasley Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@tarteo can you please review this PR?

**Pull request closed without merging**
