### PR TITLE
[MIG] website_cookiefirst: Migration to 15.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration to 15.0

### CODE REVIEW

**Review by fuentes73 — APPROVED** [review]

**Comment by gregory-moka** [comment]
Hi @fuentes73, what is blocking on this PR ?

**Comment by fuentes73** [comment]
Hi @gregory-moka more approves are needed. 
If you tested de module please approve and the OCA-git-bot will label this PR "ready to merge".

**Comment by miguel-S73** [comment]
LGTM

**Review by miguel-S73 — APPROVED** [review]

**Review by tarteo — APPROVED** [review]
Looks good to me, but I couldn't test the functionality because I dont have a Cookiefirst ID'

**Review by gregory-moka — COMMENTED** [review]
Works fine from CookieFirst to Odoo : banner & cookie policies are well implemented.
I don't understand the way a script has to be configured.
For example, Google Analytics : 
- Its configured on CookieFisrt side
- Should we disable GA from Odoo side ?

If we do so, the GA script doesn't seems to be loader even if its allowed by visitor. It's a bit complicated for me 🤔

**Pull request merged**
