### PR TITLE
[FIX] mailto links in default legal pages is malformed

### PR DESCRIPTION
**Pull request by antespi**
This fix malformed urlinks in default legal pages:

### CODE REVIEW

**Comment by antespi** [comment]
cc @pedrobaeza, @rafaelbn this is a trivial change that fix some test errors in travis. There are more unrelated test errors, affecting to all PRs in this repo.

**Comment by pedrobaeza** [comment]
:+1: Travis error unrelated

**Comment by rafaelbn** [comment]
:+1:

**Comment by JavierIniesta** [comment]
:+1:

**Pull request merged**
