### PR TITLE
[15.0][MIG]website_crm_quick_answer

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

@rafaelbn

**Review by tarteo — CHANGES_REQUESTED** [review]
The template doesn't get parsed correctly:
image

image

Am I doing something wrong?

**Comment by tarteo** [comment]
Ah I think in 15 you should use qweb like this ```<t t-out="object.name or ''">```

**Comment by manuelregidor** [comment]
> Ah I think in 15 you should use qweb like this `<t t-out="object.name or ''">`

Done

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by tarteo — CHANGES_REQUESTED** [review]
The body is parsed correctly, but ```email_from``` is still not parsed correctly I get and i guess language neither.```${object.company_id.email}``` it should be ```{{ object.company_id.email }}``` looking at other templates and odoo/tools/rendering_tools.py

**Review by tarteo — APPROVED** [review]
Thanks!

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
