### PR TITLE
[FIX] website_no_crawler: robots.txt should not be translated

### PR DESCRIPTION
**Pull request by angelmoya**
robots.txt should not be translated

It was translated from weblate.

@claudiagn check it

Is there any mechanism to prevent weblate from translating it?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Use t-translation="off"

**Comment by angelmoya** [comment]
Thanks @pedrobaeza I will do

**Comment by chienandalu** [comment]
I didn't see this. It can be closed since it's already patched in c75cf895d941365e4bdf7dd3a6e1dc4e412aacdf

**Comment by pedrobaeza** [comment]
Yes, and the fix wasn't correct.

**Pull request closed without merging**
