### PR TITLE
12.0

### PR DESCRIPTION
**Pull request by eslAmer**
this is a migrate for website_logo modules in v 12

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi @eslAmer, thanks for your first contribution. As you have seen, you have to sign the CLA. You have also to preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by eslAmer** [comment]
hi @gurneyalex @pedrobaeza , good day , can anyone please help me in this challenge cause i don't know what the error in ci/runbot and this is my first contribution , thanks guys !

**Comment by pedrobaeza** [comment]
Please start preserving commit history as requested and then we can talk :wink:

**Comment by simahawk** [comment]
handled in https://github.com/OCA/website/pull/532

**Pull request closed without merging**
