### PR TITLE
[9.0][website_snippet_big_button] Migrate

### PR DESCRIPTION
**Pull request by yajo**
- Delete CSS source.
- Use new snippets & snippet options API.
- New JS API.
- Follow guidelines and put templates under `templates/`
- LGPL.

@Tecnativa @cubells

### CODE REVIEW

**Review by cubells — APPROVED** [review]
:+1: 
Tested on runbot

**Review by rafaelbn — APPROVED** [review]
Thanks

**Comment by pedrobaeza** [comment]
@Yajo, Travis has started to fail again

**Comment by yajo** [comment]
https://github.com/OCA/server-tools/pull/666 should fix it if I'm not wrong.

**Comment by pedrobaeza** [comment]
@Yajo, tests in website are still red although the patch, and there's also an error in website_seo_redirection tests.

**Comment by pedrobaeza** [comment]
Solving server-tools problem has fixed the other problem, so this one is good to go also!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
