### PR TITLE
[14.0][ADD] website_google_analytics_4: integration to 4 generation GA

### PR DESCRIPTION
**Pull request by miguel-S73**
This module overrides the Google Analytic script in favor of integrating with Google analytic version 4.

### CODE REVIEW

**Review by matteoopenf — APPROVED** [review]
tecnical review ok

**Comment by matteoopenf** [comment]
> This module overrides the Google Analytic script in favor of integrating with Google analytic version 4.

thanks

**Review by ioans73 — APPROVED** [review]

**Comment by miguel-S73** [comment]
I have updated this PR because this last changes enable logging events (add products to cart, confirm order ...).

**Comment by miguel-S73** [comment]
After several tests, I have had to adjust the purchase event so that the purchase is actually recorded in google analytics.

**Pull request merged**
