### PR TITLE
[10.0][MIG] website_version_ce: Migration to 10.0

### PR DESCRIPTION
**Pull request by astirpe**
Based on https://github.com/OCA/website/pull/362 by @lasley, this is the porting of module `website_version_ce` to V10.

Work in progress....

### CODE REVIEW

**Comment by astirpe** [comment]
Do we really need to port the "Tours" related stuff? I think we can live with this module without tours.
This way we remove some code and we avoid maintenance and migrations for tours in future versions.

I see now, the OCB tests are green, but Odoo tests fail. It seems to me that failing tests are not related with this module.

**Comment by lasley** [comment]
@astirpe - Properly designed tests are more of a help than a hindrance and they are required per [OCA guidelines](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#tests) and in most other communities (for good reason). 

This repo currently has a testing average of 84.55%, which is a solid B. This module would drop us 23% to 61.48%, which is nearly an F.

While tours themselves are not required for the testing, I think they would be easier here than mocks or other similar strategies.

**Comment by astirpe** [comment]
@lasley ok, you convinced me :) I will port the tours as well. Thanks!

**Comment by lasley** [comment]
Let me know if you have questions on them. The v10 tours are significantly different than v9, but most of my team has now learned them quite deeply (we're still working on a damned blog post). 

Here are tour examples that I think will cover most things you'll run into:
* https://github.com/LasLabs/e-commerce/blob/683b644a1e7e6784a8682185d51f67821b18ba4c/website_sale_qty/static/tests/js/website_sale_qty.tour.js
* https://github.com/LasLabs/website/blob/0c6c7bbce68e87262539dae3615773b44ccae2cb/website_wow/static/tests/js/website_wow.editor.tour.js

**Comment by yajo** [comment]
You'll want to check this out too, it's the most similar thing to docs available nowadays AFAIK: https://www.tecnativa.com/slides/slide/the-new-way-to-develop-automated-tests-beautiful-tours-36?&

**Comment by astirpe** [comment]
@Yajo @lasley thank you very much!

**Comment by yung-wang** [comment]
Hi @astirpe , when I try to go to Menu Website Admin > Versioning > Website Domain and i click on my current website, I get the following error / traceback

```
Uncaught Error: QWeb2: Template 'website_version_ce.GoogleAccess' not found
http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:2908
Traceback:
Error: QWeb2: Template 'website_version_ce.GoogleAccess' not found
    at Object.exception (http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:2908:7)
    at Engine._render (http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:2953:103)
    at Engine.render (http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:2949:151)
    at Class.renderElement (http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:3113:1073)
    at Class.renderElement (http://83.96.206.51/web/content/2855-e04ed17/web.assets_backend.js:2221:2962)
    at Class.prototype.(anonymous function) [as renderElement] (http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:3010:559)
    at Class.renderElement (http://83.96.206.51/web/content/2855-e04ed17/web.assets_backend.js:2227:1462)
    at Class.prototype.(anonymous function) [as renderElement] (http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:3010:559)
    at http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:3113:917
    at http://83.96.206.51/web/content/2572-e124a46/web.assets_common.js:547:681
```

Can you have a look at this? Thanks.

**Comment by astirpe** [comment]
@yung-wang I cannot reproduce that error...

**Comment by yung-wang** [comment]
@astirpe There was a conflict with another module. I removed it and restart the odoo server. The error is gone now. Thanks for checking it out.

**Comment by simahawk** [comment]
@astirpe still WIP?

**Comment by astirpe** [comment]
I'm not going to work on this anymore. Sorry! Shall we close this one?

**Comment by simahawk** [comment]
@astirpe yes, then if someone needs this on v10 it can be re-opened. Thanks!

**Pull request closed without merging**
