### PR TITLE
[ADD] Add icon to files and Change where files are displayed

### PR DESCRIPTION
**Pull request by raafat-alnakar**
I added a new icon to the files (pdf - icon)
and i have changed the Where files are displayed on website

Just i  change in a file  template.xml

After
Screenshot_2019-10-24 product1

Before
website-product-cybrosys-2

### CODE REVIEW

**Comment by NL66278** [comment]
Raafat, try to make this into two commits:
- one for the unchanged module from Cybrosys (use --author=Cybrosys on the commit also);
- one for your improvement

**Comment by NL66278** [comment]
Then also do the work to bring this up to Odoo standards (and put this in a third commit)

**Comment by pedrobaeza** [comment]
But Cybrosis has signed the CLA and allow to put this into OCA?

**Comment by CybroOdoo** [comment]
We sent CLA

**Comment by pedrobaeza** [comment]
OK, good to know. Is @ralnakar included as well in that CLA? I see only commit from him. If he's copying the files instead of preserving commit attribution, I think you should be aware about that.

**Comment by NL66278** [comment]
@ralnakar should be covered by the Therp corporate CLA. Or would we need to take some specia action for that?

**Comment by pedrobaeza** [comment]
If @ralnakar is from Therp, then I think at least an initial commit from Cybrosis people may exists for proper attribution.

**Comment by Tardo** [comment]
Please, check Travis.

**Pull request closed without merging**
