### PR TITLE
12.0 website js below the fold

### PR DESCRIPTION
**Pull request by smurf-U**

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@smurf-U In Readme, use `code-gen` 
readme like this https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

**Review by tarteo — APPROVED** [review]
Thanks!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM :+1:

**Pull request merged**
