### PR TITLE
[FIX] website_google_tag_manager: Double anchor in README

### PR DESCRIPTION
**Pull request by yajo**
This was making fail other pulls, as you can see in
https://github.com/OCA/website/pull/540#issuecomment-442103775.

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this for solving the red status.

**Comment by nikul-serpentcs** [comment]
@Yajo @pedrobaeza  `Mr.Travis` is Red.

**Comment by pedrobaeza** [comment]
@nikul-serpentcs branch 11.0 is green.

**Comment by nikul-serpentcs** [comment]
> @nikul-serpentcs branch 11.0 is green.

Yes, Now is Ok.
In last day got Travis error like this: https://travis-ci.org/OCA/website/jobs/476759844#L589

and it's changed in this PR.

But Right now :cool:

**Pull request merged**
