### PR TITLE
The sass file was lying.

### PR DESCRIPTION
**Pull request by yajo**
Changed to match the CSS contents (and stop my Sass compiler's complains).

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This was a verbatim copy of an in progress PR, so maybe this is incorrect, but I didn't use it, so that's why I didn't find out.

:+1:

**Comment by yajo** [comment]
I see some tests fail, but I don't believe it's my fault.

**Comment by pedrobaeza** [comment]
It's due to the change of location of wkhtmltopdf project

**Comment by yajo** [comment]
So nothing to fix here?

**Comment by pedrobaeza** [comment]
I think so

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
