### PR TITLE
[ADD] website_logo

### PR DESCRIPTION
**Pull request by eLBati**
Load a logo image to be used on website only. This allows to use an internal company logo (for reports) and a different website logo.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't it be _website_company_logo_?

**Comment by eLBati** [comment]
Please set this WIP as module is partially broken

**Comment by nhomar** [comment]
Marked as need fixing to clarify the wip process.

**Comment by eLBati** [comment]
Thanks @nhomar , module should work now

@pedrobaeza about your question, I intentionally avoided 'company' word to distinguish between  website logo and company logo, which can be different: this module allows to set a website dedicated logo

**Comment by pedrobaeza** [comment]
Well, I think the part where the company logo is displayed is shown via the word website_ (for the frontend), opposite to web_ (for the backend).

Please check 2 PEP8 issues:

```
./website_logo/models/company.py:21:1: F401 'api' imported but unused
./website_logo/models/company.py:23:1: E302 expected 2 blank lines, found 1
```

**Comment by eLBati** [comment]
On 4 May 2015 at 21:43, Pedro M. Baeza notifications@github.com wrote:

> Well, I think the part where the company logo is displayed is shown via
> the word website_ (for the frontend), opposite to web_ (for the backend).
> 
> I mean: here logo is the logo of the website, not the company's one
> 
> Please check 2 PEP8 issues:
> 
> ./website_logo/models/company.py:21:1: F401 'api' imported but unused
> ./website_logo/models/company.py:23:1: E302 expected 2 blank lines, found 1
> 
> Fixed.

Thanks

**Comment by pedrobaeza** [comment]
But the logo isn't company-dependant? For v9, you will have the possibility of multi-site depending on the company, so I understand that the website logo should be also related to company for this situation.

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by eLBati** [comment]
Please set this as needs review

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
