### PR TITLE
Porting  website_cookie_notice and website_legal_page to 9.0

### PR DESCRIPTION
**Pull request by eLBati**
see commits

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1: travis errors unrelated

**Comment by rafaelbn** [comment]
Rebuilind for testing

**Comment by rafaelbn** [comment]
@eLBati  runbot it's failing I cannot rebuild

**Comment by eLBati** [comment]
@rafaelbn you should be able to test at http://3136852-106-ee2f1b.runbot2.odoo-community.org/

About travis, I am not able to reproduce the error locally (with latest revision of odoo).

@OCA/website-maintainers could you restart the build https://travis-ci.org/OCA/website/builds/90513632 ?

**Comment by rafaelbn** [comment]
hi @eLBati , in you link:

**Comment by eLBati** [comment]
Something weird is happening to runbot

**Comment by eLBati** [comment]
Rebuilded travis, still red :broken_heart:

**Comment by antespi** [comment]
New commits have been done in branch 8.0. They could be merged here, isn't it?
https://github.com/OCA/website/commits/8.0/website_cookie_notice

**Comment by lasley** [comment]
Looks like we're missing a few commits that have been added since this PR was last worked on: 

`website_legal_page`
- e4ec66d949e216227d03c70b94b28736cbd3dd6c
- ce30f77d5fd6756e21b2130b06ff3e92ef632580

`website_cookie_notice`
- bdfd7ff346ca0feb8b1a2cbad266ba79c8c737fc
- 2e544b946c20b77e1fdc3d6d59ec202b7cae31eb
- 98a19f7836ec4ccf5ceeff4c876fcf42e56b0524
- 957f74462ccabd3e66d8c85f236c0d713723808a

There were a few others, but they spanned multiple modules so will be hard to cherry pick in.

**Comment by eLBati** [comment]
@antespi @lasley made another branch including last changes from 8.0 version at https://github.com/OCA/website/pull/195
I removed `website_legal_page` from the PR, as ported by https://github.com/OCA/website/pull/194

**Pull request closed without merging**
