### PR TITLE
[ADD] [13.0] Web Core Vitals: Prevent Cumulative Layout Shift

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Review by Kiplangatdan — APPROVED** [review]
Nice feature.
Works well on v13 CE.

**Review by tarteo — APPROVED** [review]
LGTM!

**Comment by gfcapalbo** [comment]
@thomaspaulb @Kiplangatdan very nice idea , merging in , the advantages of precise height/width can be used specifically by users that want that type of optimization.

**Pull request merged**
