### PR TITLE
[IMP][8.0]website_portal_purchase: change h3 tittle attribute

### PR DESCRIPTION
**Pull request by sergio-teruel**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Why travis fails?

**Comment by yajo** [comment]
Affected by #152 too.

**Comment by yajo** [comment]
:+1: to code review, but I cannot test in runbot.

**Comment by sergio-teruel** [comment]
@Yajo @rafaelbn Rebase done

**Comment by antespi** [comment]
You should consider to do the same here https://github.com/OCA/website/blob/8.0/website_product_supplier/views/product_supplier_view.xml#L155

**Comment by antespi** [comment]
:+1: 
OK, you've done here https://github.com/OCA/website/pull/153/files#diff-123c4bac77679a6aa8b1c89c403978d3R155, cool

**Comment by yajo** [comment]
:+1:

**Comment by rafaelbn** [comment]
Ok, thanks! :+1:

**Pull request merged**
