### PR TITLE
[MIG] [9.0] website_menu_by_user_status

### PR DESCRIPTION
**Pull request by hurrinico**

### CODE REVIEW

**Comment by lasley** [comment]
@hurrinico - please rebase onto the current 9.0 to fix up the SASS issues in Travis

**Comment by hurrinico** [comment]
@lasley i'm quite late :D but i've rebased and the pr is green!

**Review by eLBati — CHANGES_REQUESTED** [review]
Tried on runbot
http://3280408-275-5760f3.runbot2.odoo-community.org/:
removed ```User Not Logged``` from ```Forum``` menu.
Opening http://3280408-275-5760f3.runbot2.odoo-community.org/ with private session, I can see the forum menu

**Comment by tarteo** [comment]
Hi, I tried to test it on runbot but unfortunately I couldn't due to an error (not related to this module):
image

**Comment by pedrobaeza** [comment]
It was fixed meanwhile. You can rebase. @lasley is now out of Odoo, so don't expect him to make anything more. You can superseed this PR.

**Comment by simahawk** [comment]
@hurrinico @eLBati ping :)

**Comment by simahawk** [comment]
@hurrinico I'll provide you a base to backport via this https://github.com/OCA/website/pull/394
and we gonna have the same base for v8 too https://github.com/OCA/website/pull/509 that will be:
website_menu_permissoin to handle the real permission machinery and website_menu_by_user_status only to provide the quick flag

**Comment by eLBati** [comment]
For me this can be closed

**Comment by simahawk** [comment]
@eLBati fine :)

**Pull request closed without merging**
