### PR TITLE
[13.0][MIG] website_snippet_marginless_gallery: Migration to 13.0

### PR DESCRIPTION
**Pull request by Tardo**
Normal migration only changes to use the new api calls to run tours

cc @tecnativa TT27595

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Functional review in runboat

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by chienandalu — APPROVED** [review]
Tested :-1: Thanks :)

**Pull request merged**
