### PR TITLE
[13.0][ADD] website_cookiefirst: Cookiefirst integration

### PR DESCRIPTION
**Pull request by ioans73**
Integrates Odoo website with GDPR through the functionality of Cookiefirst.

### CODE REVIEW

**Review by bosd — APPROVED** [review]
Oddly enough the module description is empty.
image

**Comment by bosd** [comment]
It was not very clear that the icon was a cookie. Maybe this is an interesting suggestion.

icon

**Review by fuentes73 — APPROVED** [review]

**Comment by ioans73** [comment]
@bosd the readme is generated when the PR is merged

**Review by claudiagn — APPROVED** [review]
LGTM! 👍

**Review by manuelcalerosolis — APPROVED** [review]
LGTM! please merge

**Pull request merged**
