### PR TITLE
migrated website_analytics_piwik to 12.0

### PR DESCRIPTION
**Pull request by jans23**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by Tardo** [comment]
ping @jans23

**Comment by Tardo** [comment]
Other contributor started the migration of this module before: https://github.com/OCA/website/pull/697

**Comment by jans23** [comment]
> Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

I know the commit history should have been preserved but it wasn't done unfortunately. We only have the code without history. Still something we could continue with?

**Comment by Tardo** [comment]
Try this (remote alias: origin, migration from: 11.0):

1. Squash your PR commits (if needed) and get the commit hashes:
```git log --oneline```

2. Get latest status of the remote repo
```git fetch origin```

3. Reset your branch to be like remote branch
```git reset --hard origin/12.0```

4. Get commit history about 'website_analytics_piwik' module from 11.0 to 12.0
```git format-patch --keep-subject --stdout origin/12.0..origin/11.0 -- website_analytics_piwik | git am -3 --keep```

5. Restore your work (using the hashes that you got in the first step). Perhaps you need resolve some conflicts... do it.
```git cherry-pick bd9717855f367a1ff9c7a3c55ad59598bdb8c587```

**Review by LoisRForgeFlow — COMMENTED** [review]
Tested it and work fine :+1: 

I will approve when @tardo comments are attended

**Review by claudiagn — APPROVED** [review]
functional review ok! 👍

**Comment by kwoot** [comment]
I tried to test this addon with a Matomo server that has the ProtectTrackID plugin activated. This means the SiteID is not an integer but a string. The Odoo settings page borks on this. Other than that it seems to work with an integer SiteId.

May I suggest also to switch from calling piwik.php etc to matomo.php.

**Pull request closed without merging**
