### PR TITLE
Restructure website_cookie_notice.

### PR DESCRIPTION
**Pull request by yajo**
This will allow automatic translations and easier maintenance.

Many code has been removed to simplify eveything.

We are losing slovenian translation with this, I hope they can translate it again soon. Anyway, that translation was not working (see previous PR: https://github.com/OCA/website/pull/87)...

CC @rafaelbn @sergio-incaser @pedrobaeza @eLBati.

### CODE REVIEW

**Comment by eLBati** [comment]
Thanks @Yajo , please rebase to include https://github.com/OCA/website/pull/97

**Comment by yajo** [comment]
Rebased.

This is a very big refactoring, but let me summarize so you understand the code.
- I removed all CSS & JS.
  - There is a tiny JS file now that just makes the link to load the controller by AJAX.
- Instead of saving a cookie to know if the user accepted them, it is saved in the session.
  - This is done in a very simple controller that redirects to the main page just in case somebody disables JS and gets there by plain HTTP request.
- The notice is printed through the main layout qWeb view into a `t-if` clause that checks the session variable.
  - It has bootstrap classes to avoid adding more CSS for this module.
  - It has class `cc-cookie` like before, to not break [much] themes depending on this out there.
- All fields from res.company are removed because of translation bug found in #87. If any admin wants to change the message, there are now 2 options:
  - Modify views and translations manually from Odoo backend.
  - Do the same in a submodule.
- It links to legal terms made by module `website_legal_page`.

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Comment by dgzurita** [comment]
Tested in runbot :+1:

**Comment by janetrp** [comment]
tested :+1:

**Comment by rafaelbn** [comment]
Hi @eLBati This module is ready to merge but I would like to have your review before merging. Thanks

**Comment by yajo** [comment]
Last commit should fix Travis.

**Comment by yajo** [comment]
Please review [last commit message](https://github.com/Yajo/website/commit/c6968e81eff063b922ee77c46c1341008d00cf57).

**Comment by eLBati** [comment]
@Yajo @rafaelbn thanks for the changes. In general, I am :+1: 
Still open question from @pedrobaeza at https://github.com/OCA/website/pull/96#commitcomment-14108656

**Comment by yajo** [comment]
New warning committed.

I know introducing breaking changes is cumbersome, but keep in mind that actually I am fixing an already broken behavior as discussed in #87. Tests have proven that there is no way to fix this without breaking it too AFAIK. I hope you understand.

**Comment by eLBati** [comment]
Thanks @Yajo , do you know why travis is red?

**Comment by yajo** [comment]
No idea, seems not related and only fails in OCB.

**Comment by rafaelbn** [comment]
@pedrobaeza all clear? could we merge?

**Pull request merged**
