### PR TITLE
[16.0][MIG] website_cookiefirst: Migration to 16.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration

### CODE REVIEW

**Comment by matteoopenf** [comment]
I made a fix in 14.0, I think you should evaulte to port  the fix

**Comment by NICO-SOLUTIONS** [comment]
Functional review..
looks good to me

**Comment by ao-landoo** [comment]
@ioans73 Can you rebase or apply commit @matteoopenf is mentioning?

**Comment by ioans73** [comment]
@ao-landoo @matteoopenf is this commit?https://github.com/OCA/website/commit/ffe59df28126c28b5330b90a3378cc35d728071a

**Comment by matteoopenf** [comment]
> @ao-landoo @matteoopenf is this commit?https://github.com/OCA/website/commit/ffe59df28126c28b5330b90a3378cc35d728071a

I confirm, thanks

**Review by ao-landoo — APPROVED** [review]
Technical approval

**Comment by matteoopenf** [comment]
> Technical approval

I don't see my commit ...

**Comment by ao-landoo** [comment]
Was your commit taken to V15?

**Comment by ioans73** [comment]
Finally I have modified the xpath, but keeping the same template, since that element is added in `website.footer_copyright_company_name` and not in `website.layout`

**Comment by matteoopenf** [comment]
> Was your commit taken to V15?

is in 14.0 https://github.com/OCA/website/commit/ffe59df28126c28b5330b90a3378cc35d728071a

**Comment by matteoopenf** [comment]
> Was your commit taken to V15?

also in 14.0 broken if threre isn't the fix the translation is broken

**Review by fuentes73 — APPROVED** [review]

**Comment by ioans73** [comment]
@OCA/website-maintainers could you merge please?

**Comment by ioans73** [comment]
@pedrobaeza could you merge please?

**Pull request merged**
