### PR TITLE
[ADD] Adding New Module website_membership_contact_visibility

### PR DESCRIPTION
**Pull request by mikevhe18**

### CODE REVIEW

**Comment by mikevhe18** [comment]
@pedrobaeza 
I've changed the name of this module. I also remove the message "_Contact information has been marked as private. For more information please contact administrator_" and make it only has 2 choices : "Publish" that means visible on the website or "Unpublish" which means not visible on the website. If later, still there is someone who needs the contact information of the member, that person can still access the contact us page  and send an email.

**Comment by pedrobaeza** [comment]
Thanks for the renaming!

:+1:

**Comment by oscarolar** [comment]
I've been using the feature on runbot, don't you think that the 'Visible on the website'  label should change for something like 'Contact Info On Website'?, to me the 'Visible on the website' label is for the whole record, like all the models that have the `website_published` field, I think its a little bit confusing 
va

**Comment by mikevhe18** [comment]
@pedrobaeza Ah, you're right. It's the little things i didn't notice that will be confusing for people who use this module. Thank you for the review. I'll replace it soon.

**Comment by mikevhe18** [comment]
@pedrobaeza sorry, i was wrong mention. Actually, my previous comment was for @oscarolar

**Comment by mikevhe18** [comment]
@pedrobaeza @oscarolar If you have time, would you kindly review this module again ?

**Comment by oscarolar** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Hi, I have moved the module to https://github.com/OCA/vertical-association/tree/8.0/website_membership_contact_visibility, because it's a better place for storing it, as there is a dedicated vertical project.

**Comment by rafaelbn** [comment]
Hi @mikevhe18, which is the public URL where you can see members?

**Comment by rafaelbn** [comment]
Sorry, it's http://3142585-8-0-a474d2.runbot1.odoo-community.org/members ...

**Pull request merged**
