### PR TITLE
[17.0][MIG] website_require_login: Migration to 17.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
Standard Migration

### CODE REVIEW

**Comment by esafocus** [comment]
I installed and tested the module, it seems to work well apart from this error in the logs, after installation

2022-05-31 10:14:14,119 2368 INFO erp odoo.modules.registry: module website_require_login: creating or updating database tables
2022-05-31 10:14:14,144 2368 WARNING erp py.warnings: /opt/odoo/odoo/odoo/addons/base/models/ir_module.py:170: DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, website_require_login can just have a UTF8 description with not need for a declaration.
  File "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/opt/odoo/odoo-venv/lib/python3.11/site-packages/werkzeug/serving.py", line 342, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.11/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/opt/odoo/odoo-venv/lib/python3.11/site-packages/werkzeug/serving.py", line 374, in handle_one_request
    self.run_wsgi()
  File "/opt/odoo/odoo-venv/lib/python3.11/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/odoo-venv/lib/python3.11/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 2150, in __call__
    response = request._serve_db()
  File "/opt/odoo/odoo/odoo/http.py", line 1722, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/odoo/http.py", line 1749, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/odoo/http.py", line 1953, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-custom-addons/apps/website_require_login/models/ir_http.py", line 17, in _dispatch
    return super()._dispatch(endpoint)
  File "/opt/odoo/odoo/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-83>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 650, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 583, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    module._check()
  File "/opt/odoo/odoo/odoo/addons/website/models/ir_module_module.py", line 478, in _check
    super()._check()
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 832, in _check
    if not module.description_html:
  File "/opt/odoo/odoo/odoo/fields.py", line 1206, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/odoo/models.py", line 4858, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/odoo/fields.py", line 101, in determine
    return needle(*args)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_module.py", line 170, in _get_desc
    warnings.warn(

**Comment by NICO-SOLUTIONS** [comment]
This is a warning that the index file has encoding defined which is deprecated for odoo17. This will be fixed by pre commit when the dotfiles are updated.

**Comment by SonoDavid** [comment]
Is this branch to be merged or are there still some problems?

**Comment by pedrobaeza** [comment]
@SonoDavid put your review in this pull request to favor the merge.

https://odoo-community.org/resources/review
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Comment by SonoDavid** [comment]
Functional review LGTM

**Review by yvaucher — APPROVED** [review]
LGTM

Code review

**Comment by yvaucher** [comment]
@SonoDavid reviews comment can be done in the files changes tab, it tags your comment as review and ease the count of the reviews to validate PRs.

With your PR we have the 2 necessary reviews, I will merge it now.

**Comment by NICO-SOLUTIONS** [comment]
things are moving forward...
thanks @yvaucher

**Pull request merged**
