### PR TITLE
[9.0][MIG] website_backend_views to v9

### PR DESCRIPTION
**Pull request by lasley**
This upgrades website_backend_views to v9.

It should work, although I haven't tested much. This is a WIP because with the fix I found in OCA/web#402 for [public data sessions](https://github.com/OCA/web/pull/402/commits/33ee3ae91e66e687af7cab6195383ffd2ac2456d), I believe this is the key for OCA/web#403 instead of the standalone session module.

### CODE REVIEW

**Comment by simahawk** [comment]
@lasley sorry, just to clarify: do I need to wait for the linked issues to be closed or can I test the porting right away? tnx

**Comment by lasley** [comment]
@simahawk - I just pushed the version that I have been functionally testing before implementing the public session. This should work in v9 to the same capacity that the v8 one did, and I would most certainly love additional confirmation 😄

**Comment by simahawk** [comment]
`website.assets_frontend.js:836 Uncaught TypeError: openerp.init is not a function` this is what I get :(
The whole error in debug mode is [this](https://www.dropbox.com/s/vdfiesb2te5ll2h/bkend-views-err.png?dl=0).

**Comment by simahawk** [comment]
closing as it's on 9.0 and no action since more than 2 yrs and @lasley left us a long time ago :sob: 
Feel free to re-open it if anyone needs it, thanks!

**Pull request closed without merging**
