### PR TITLE
[FIX] website_portal_sale: Order list indicates "Invoiced" state when…

### PR DESCRIPTION
**Pull request by eantones**
… order is "In progress" and not necessarily invoiced yet.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
That was backported from v9, so maybe there's a reason for that label. @sergio-incaser @carlos-incaser, do you know it?

**Comment by sergio-teruel** [comment]
In odoo  v9.0 this state is marked as invoiced:
https://github.com/OCA/OCB/blob/9.0/addons/website_portal_sale/views/templates.xml#L80
However i think that @eantones has the reason, but @pedrobaeza i think that this PR also must be proposed to Odoo/Ocb 9.0.
@eantones can you propose to Odoo?  Thanks
For this PR :+1:

**Comment by pedrobaeza** [comment]
OK then for this :+1:

And for the patch to Odoo, they don't usually accept any translation change on stable branch, but you can try.

**Comment by carlosdauden** [comment]
:+1:

**Comment by eantones** [comment]
Ok, thanks!!

I'll try to propose it in odoo/ocb 9.0 or odoo/odoo 9.0 directly.

Thanks again

**Pull request merged**
