### PR TITLE
[8.0][FIX][website_cookie_notice] Cookie message translation

### PR DESCRIPTION
**Pull request by antespi**
Remove enters and spaces to avoid problems with translation of cookie message

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Change version number

**Comment by antespi** [comment]
You're right @pedrobaeza, Thanks. Done

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: Fast-tracking when CIs finish

**Pull request merged**
