### PR TITLE
[14.0][MIG] website_cookie_notice

### PR DESCRIPTION
**Pull request by ivantodorovich**
Standard migration

Please note there have been some discussions about this module questioning its GPDR compliance: https://github.com/OCA/website/issues/696

This PR does not try to solve those issues, it simply migrates the existing features.
Hopefully odoo will consider this https://github.com/odoo/odoo/pull/61946 :eyes:

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Travis and runbot are failing due to unrelated errors

**Review by robyf70 — APPROVED** [review]
LGTM

**Review by mmarcot — APPROVED** [review]
LGTM
However, cookie banner message translations are truncated

**Review by manuelregidor — APPROVED** [review]
LGTM

**Review by angelmoya — APPROVED** [review]
:+1: LGTM

**Comment by jado95** [comment]
Who can merge this?

**Review by jado95 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Odoo already includes a cookie notice in this version, isn't it?

**Comment by jado95** [comment]
> Odoo already includes a cookie notice in this version, isn't it?

Yes you are right. At this point the PR can also be closed, right?

**Pull request closed without merging**
