### PR TITLE
Website sale categories megamenu

### PR DESCRIPTION
**Pull request by yajo**
Add a product categories megamenu to online shop.

cc @rafaelbn.

### CODE REVIEW

**Comment by dgzurita** [comment]
Nice! Tested in runbot :+1:

**Comment by moylop260** [comment]
Do you added the left menu of next image?
categ_tree

**Comment by moylop260** [comment]
Could you add a image in README.txt file of that you added?

**Comment by rafaelbn** [comment]
Wow! Supermegamenú!!!! Al least a real menú for categories! Tested in runbot :+1:

**Comment by rafaelbn** [comment]
Please move this PR to https://github.com/OCA/e-commerce, this is only for website_sale

```
+    "depends": [
+        "website_sale",
```

**Comment by antespi** [comment]
:+1: tested in runbot and code review

**Comment by yajo** [comment]
Moving this to e-commerce.

**Pull request closed without merging**
