### PR TITLE
[MIG] website_portal_contact: Migration to 10.0

### PR DESCRIPTION
**Pull request by OsoTranquilo**
It is the migration of the module website_portal_contact to version 10 of Odoo.
The dependencies of the old "website_portal_v10" have been changed to the new one "website_portal"
The references have been changed in the rendering of the pages, and in the description of the fields the call to the value 'help' for the one of 'string'

### CODE REVIEW

**Review by yajo — CHANGES_REQUESTED** [review]
Travis says [the tour is broken](https://travis-ci.org/OCA/website/jobs/237482139#L1022-L1183).

Tours have changed in v10. Check the docs in https://www.tecnativa.com/slides/slide/the-new-way-to-develop-automated-tests-beautiful-tours-36 and please update the js tour definition.

**Comment by pedrobaeza** [comment]
@OsoTranquilo are you going to fix this PR?

**Comment by OsoTranquilo** [comment]
Sorry for the delay. It's already working. And as soon as it's approved, I try it for version 11. ¿o.k.?

**Review by simahawk — CHANGES_REQUESTED** [review]
@OsoTranquilo pls
1. keep module's commit history https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
2. fix build
3. squash commits once you are done w/ above points :)
Thanks!

**Pull request closed without merging**
