### PR TITLE
[8.0][website_anchor_smooth_scroll] Smooth scrolling on anchors.

### PR DESCRIPTION
**Pull request by yajo**
Get it for free for all of your `<a href="#whatever">Move me</a>` elements!

@rafaelbn

### CODE REVIEW

**Comment by rafaelbn** [comment]
Functional :+1:

**Comment by rafaelbn** [comment]
cc @antespi @danielgz

**Comment by pedrobaeza** [comment]
Can you please create some demo data like the container fluid to try in a more straight way?

**Comment by yajo** [comment]
@pedrobaeza done.

**Pull request merged**
