### PR TITLE
 [13.0][MIG] website_form_recaptcha

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by simahawk** [comment]
it's already done here https://github.com/OCA/website/pull/684

**Comment by bizzappdev** [comment]
wow, I see now. https://github.com/OCA/website/issues/667 This was not up to date and that is why I migrated it again.

**Comment by simahawk** [comment]
> wow, I see now. #667 This was not up to date and that is why I migrated it again.

yep, sorry for this. There's no automation there. In any case, before starting any new PR it's always a good thing to search by milestone and module name :wink:

**Comment by pedrobaeza** [comment]
The automation is in progress in https://github.com/OCA/oca-github-bot/pull/97 :wink:

**Comment by simahawk** [comment]
> The automation is in progress in [OCA/oca-github-bot#97](https://github.com/OCA/oca-github-bot/pull/97)

I know! Thanks for it! I had a mental note somewhere to review it :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
