### PR TITLE
[IMP][8.0] website_portal: Change templates to group sales and purchases.

### PR DESCRIPTION
**Pull request by sergio-teruel**
This change allow show tabs in my account page

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@rafaelb @carlos-incaser Needs review here. Minimal changes

**Comment by hbrunn** [comment]
:+1:

**Comment by rafaelbn** [comment]
Ok, thanks :+1:

**Comment by carlosdauden** [comment]
:+1:

**Pull request merged**
